### PR TITLE
OSS: address unused argument warnings

### PR DESCRIPTION
**Pull request by mathstuf**

### CODE REVIEW

**Comment by mathstuf** [comment]
The warnings showed up in code using OpenTURNS. Warnings are [here](https://open.cdash.org/viewBuildError.php?type=1&buildid=4800663).

**Comment by mathstuf** [comment]
Hmm, I didn't scroll down in the first box. There are more warnings it seems :) . Followup commits incoming.

**Comment by regislebrun** [comment]
@mathstuf I suppose that you are working on a paraview feature based on OpenTURNS. It could be a good idea to exchange through the dedicated mailing list (developers@openturns.org, see http://openturns.org/mailman/listinfo/developers) since there are some tricks to know to get an efficient implementation of multiple minimum level sets computations. You can also send me a message at regis.lebrun_AT_m4x.org

**Comment by regislebrun** [comment]
otherwise, +1

**Comment by mathstuf** [comment]
Thanks. I'm the one in charge of getting the build environments set up; I'll link your comment to the developer adding the support.

**Comment by mwestphal** [comment]
I sent a mail trough the ml.

**Comment by regislebrun** [comment]
@mwestphal Not received yet. @jschueller Is the developers mailing list still active? Am I still registered on this list with my personal account?

**Comment by mwestphal** [comment]
Here is a copy of my mail just in case :
Hello OpenTurns community

We (Kitware) are implementing a (small) openturns filter for VTK/ParaView.
We used it with success so far, but i'm more a programmer than a math expert,
so if you want to take a look and give us some advices, please do so.

https://gitlab.kitware.com/vtk/vtk/merge_requests/2513

One filter compute Kernel Smoothing for plotting, while the other compute density map
on could points.

Regards,

Mathieu Westphal

**Comment by regislebrun** [comment]
@mwestphal How can I comment directly on gitlab.kitware.com? I have some remarks you may find useful on your code ;-).

**Comment by mwestphal** [comment]
@regislebrun : this is an open gitlab. you can register, validate your email (check your spam) and you should be able to comment on the link in the comment above.

**Pull request merged**
