### PR TITLE
Remove library wrapper

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by sofianehaddad** [comment]
+1

**Comment by jschueller** [comment]
I removed the mingw wrapper example in distro/windows too

**Comment by dbarbier** [comment]
+1

**Comment by regislebrun** [comment]
+1

**Comment by dbarbier** [comment]
Since this pull request had been merged, there are new compilation warnings:

```
/home/travis/build/openturns/openturns/lib/src/Base/Geom/Mesh.hxx:84: Warning 509: Overloaded method OT::Mesh::getNearestVertexIndex(OT::NumericalSample const &) const effectively ignored,
/home/travis/build/openturns/openturns/lib/src/Base/Geom/Mesh.hxx:78: Warning 509: as it is shadowed by OT::Mesh::getNearestVertexIndex(OT::NumericalPoint const &) const.
/home/travis/build/openturns/openturns/lib/src/Base/Geom/Mesh.hxx:87: Warning 509: Overloaded method OT::Mesh::getNearestVertex(OT::NumericalSample const &) const effectively ignored,
/home/travis/build/openturns/openturns/lib/src/Base/Geom/Mesh.hxx:81: Warning 509: as it is shadowed by OT::Mesh::getNearestVertex(OT::NumericalPoint const &) const.
...
```

See https://s3.amazonaws.com/archive.travis-ci.org/jobs/82017867/log.txt

**Comment by jschueller** [comment]
Weird, both are tested in Mesh_std.py

**Comment by dbarbier** [comment]
May be related to http://sourceforge.net/p/swig/bugs/1053/
`OT_TYPECHECK_NUMERICALPOINT` and `OT_TYPECHECK_NUMERICALSAMPLE` are both defined to 5, warnings go away when setting different values.

**Pull request merged**
