### PR TITLE
Added a specialization of Field::draw() for 2D fields over 2D domains.

### PR DESCRIPTION
**Pull request by regislebrun**
Also fixed a bug in Field::drawMarginal() when interpolate == true

### CODE REVIEW

**Comment by jschueller** [comment]
test still fail when printing graph values

**Comment by regislebrun** [comment]
@jschueller hopefully this time it is fixed...

**Comment by jschueller** [comment]
The python test still fails, maybe avoid printing graphs ?

**Comment by regislebrun** [comment]
Done

**Comment by regislebrun** [comment]
@jschueller found another bug, commit in a few minutes

**Comment by regislebrun** [comment]
pyinstallcheck_Viewer failed, is it solved by PR#458?

**Comment by jschueller** [comment]
maybe unrelated, #458 only fixes a segfault on osx

**Comment by regislebrun** [comment]
ok. I removed all the output of the tests as muparser gives slightly different results on the different machines, resulting in different rounding and a different number of segments in the output.

**Pull request merged**
