### PR TITLE
Add DiscreteCompoundDistribution class

### PR DESCRIPTION
**Pull request by jschueller**
Squared things up from #1135, cc @josephmure

### CODE REVIEW

**Comment by josephmure** [comment]
Thanks for updating  #1135, @jschueller !

The title of this pull request should probably be changed to _Add DiscreteCompoundDistribution class_ since this is the actual name of the class.

**Comment by regislebrun** [comment]
Good to go. You may consider applying the joined patch. The following benchmark:
```
import openturns as ot
distribution = ot.DiscreteCompoundDistribution(ot.Geometric(0.05), ot.Poisson(20.0))
size = 100000000
from time import time
t0 = time()
res = distribution.getSample(size)
t1 = time()
print("Speed=", size / (t1 - t0), "rng/s")
t0 = time()
pdf = distribution.computePDF(res)
t1 = time()
print("Speed=", size / (t1 - t0), "pdf/s")
```
gives
```
Speed=  7749369.915098633 rng/s
Speed=  8677572.554475648 pdf/s
```
without the patch and
```
Speed= 12897197.750293972 rng/s
Speed= 31365194.14238751 pdf/s
```
with the patch, ie x1.7 for the sampling speed and x3.6 for the pdf speed.

[improve_compound_distribution.zip](https://github.com/openturns/openturns/files/3685146/improve_compound_distribution.zip)

**Comment by jschueller** [comment]
@regislebrun done

**Comment by regislebrun** [comment]
+1

**Pull request merged**
