### PR TITLE
Improve resource map

### PR DESCRIPTION
**Pull request by regislebrun**
Now, there are separated maps for String, Scalar, UnsignedInteger and Bool in order to avoid costly conversions.

### CODE REVIEW

**Comment by jschueller** [comment]
Did you push the parallel-threads fix ?
```
ResourceMap.cxx:343:51: error: invalid conversion from 'char*' to 'OT::UnsignedInteger {aka long unsigned int}' [-fpermissive]
   setAsUnsignedInteger( "parallel-threads", getenv("NUMBER_OF_PROCESSORS") );
```

**Comment by jschueller** [comment]
One drawback is that the user has to use the right api to set a value.
Consider SquaredExponential-DefaultTheta, in http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.ResourceMap.html, look at ```SquaredExponential-DefaultTheta``` it is displayed as ```1``` but the user doesnt know if it's a float or an int, and whether he should use setAsUnsignedInteger or setAsScalar.
Can we infer the type of a key with the new API ? At least there should be a "Type" column in that documentation.

**Comment by jschueller** [comment]
Another idea would be keeping the single string map but to cache converted values.

**Comment by regislebrun** [comment]
I am not very fond of the cache idea. I added a type accessor to ResourceMap and enhanced the documentation, IMO it is enough to make the user happy.

**Comment by sofianehaddad** [comment]
Needs a rebase

**Comment by regislebrun** [comment]
rebase done, everything looks alright, no?

**Comment by jschueller** [comment]
Ok for me.

**Pull request merged**
