### PR TITLE
Bugfix covariance model

### PR DESCRIPTION
**Pull request by sofianehaddad**
The following PR fixes a bug in CovarianceModelImplementation::setParameter and introduce new constructor to ExponentialModel

### CODE REVIEW

**Comment by jschueller** [comment]
+1, next time try to shorten commit title, skip a line and add a longer description if needed.

**Comment by sofianehaddad** [comment]
@jschueller agreed. Fixed

**Comment by dbarbier** [comment]
+1

**Comment by regislebrun** [comment]
+1

**Pull request merged**
