### PR TITLE
Fix Path::GetExecutableDirectory on osx

### PR DESCRIPTION
**Pull request by jschueller**
/proc/ is not available to read the exe path
use _NSGetExecutablePath system call

### CODE REVIEW

**Comment by dbarbier** [comment]
This method does not make sense, couldn't we instead just drop it?

**Comment by jschueller** [comment]
@dbarbier I use it to guess the config dir location when the install tree is moved around, like in conda.
I agree this is a bit hackish, but it's the only thing I could come up with.

**Comment by jschueller** [comment]
@dbarbier any other idea ?

**Comment by dbarbier** [comment]
@jschueller I do not know conda, it seems that http://conda.pydata.org/docs/building/meta-yaml.html#relocatable discusses this issue

**Comment by jschueller** [comment]
@dbarbier
Our problem is that ot searches for the config file in env vars or compile-time prefix.
In the context of conda we cannot set env vars easily, and the installation prefix is different from the compile-time prefix and conda doesn't help us to replace the compile-time prefix as it resides in the library and not text files.

**Comment by dbarbier** [comment]
Prefix can be replaced in binary file too, see the 3rd item.

**Comment by jschueller** [comment]
@dbarbier, indeed

**Comment by sofianehaddad** [comment]
hmmm the problem with conda is indeed solved. But the current master still generates error due to bad readlink (thus tests fail and library loads with an error...)

**Comment by jschueller** [comment]
@sofianehaddad, I propose to only use GetExecutableDirectory on windows.

**Comment by sofianehaddad** [comment]
@jschueller ok

**Comment by jschueller** [comment]
@sofianehaddad, see #225

**Pull request closed without merging**
