### PR TITLE
Allow to serialize nan/inf values

### PR DESCRIPTION
**Pull request by jschueller**
Nan/inf values are correctly written to xml, but converted to 0 when reading back.

### CODE REVIEW

**Comment by dbarbier** [comment]
If you want to support reading inf/nan, this must be done for all numeric types, not only Scalar.

**Comment by jschueller** [comment]
@dbarbier ok

**Comment by regislebrun** [comment]
+1

**Comment by jschueller** [comment]
cc @aurelieladier

**Pull request merged**
