### PR TITLE
Symmetrize matrices on array conversion

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by dbarbier** [comment]
+1
Wow, I don't understand how it works, thanks for fixing this.

**Comment by jschueller** [comment]
@dbarbier the trick is to overload the array interface query '__array_interface__' already intercepted by Matrix.getattribute in SymmetricMatrix.getattribute to symmetrize the object.

**Comment by regislebrun** [comment]
+1

**Comment by sofianehaddad** [comment]
+1

**Pull request merged**
