### PR TITLE
Update plot_sensitivity_wingweight.py

### PR DESCRIPTION
**Pull request by m-balesdent**
Modification of example to have shaded surfaces instead of contours to ease the interpretation of the influence of the variables following past technical committee recomandations.

### CODE REVIEW

**Comment by jschueller** [comment]
you probably want to change target branch to 1.20

**Comment by m-balesdent** [comment]
Actually it's a patch for current RC1

**Comment by jschueller** [comment]
yes, so it should go to the 1.20 branch to land in the final v1.20 tag

**Comment by m-balesdent** [comment]
transfer to 1.20

**Pull request closed without merging**
