### PR TITLE
Copulas related enhancements

### PR DESCRIPTION
**Pull request by jschueller**
- ComposedCopula::getMarginal to handle non-contiguous dependency blocs
- MarginalDistribution::isCopula correctly handles the isCopula flag

use case:
https://gist.github.com/jschueller/7585cf999a0f1104d451e23c43024768

### CODE REVIEW

**Comment by regislebrun** [comment]
+1 A further improvement would be to check if several contiguous copulas are normal copulas, in which case it would be possible to deal with indices mixing different contiguous blocks. The benefit would be to avoid to use MarginalDistribution, which is a kind of "last chance" option. I was too lazy to implement it when I proposed the ComposedCopula class, shame on me. It can wait for another PR.

**Comment by jschueller** [comment]
If several copulas are Normal, this could even be dealt with at the construction of the object. This is also true for the independent copula.

**Comment by regislebrun** [comment]
@jschueller The simplification has to be done with care: the merge of two independent copulas is harmless in terms of speed and memory, but the merge of two normal copulas can have a bad impact on both. Think about a ComposedCopula made of N NormalCopula instances of dimension 2. The composed copula stores (and computes) 4N correlations while the full normal copula uses 4N^2 correlations. My point was to avoid the use of MarginalDistribution as much as possible, because it implies the evaluation of the full underlying distribution even if the marginal is of significantly lower dimension.

**Comment by jschueller** [comment]
ok I understand.

**Comment by jschueller** [comment]
@regislebrun I added the example in this branch

**Comment by jschueller** [comment]
@dbarbier are you okay with those changes ?

**Pull request merged**
