### PR TITLE
Update copyright year

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
@dbarbier, maybe this can be done while moving headers ?

**Comment by sofianehaddad** [comment]
+1

**Comment by regislebrun** [comment]
+1

**Comment by dbarbier** [comment]
@jschueller Sorry, I was away.  I can move headers into this PR, but you will have to give me write access.  Or I make a regular PR just after your merge, as you want.

**Comment by jschueller** [comment]
@dbarbier, you can make a regular pr with all the changes together, i'll cancel this one, I only ran copyright.sh.

**Pull request closed without merging**
