### PR TITLE
Cleanup optimization API

### PR DESCRIPTION
**Pull request by jschueller**
1.- The solvers *SpecificParameters classes are deprecated as parameters are transfered to solvers as attributes, docstrings were added so as to solve http://trac.openturns.org/ticket/790
2.- I thought OptimizationSolverImplementationResult could be renamed to OptimizationResult
3.- checkProblem should be private

### CODE REVIEW

**Comment by jschueller** [comment]
@dbarbier, ok, fixed and squashed

**Comment by dbarbier** [comment]
I have mixed feelings about the last commit, okay for other ones.

**Comment by jschueller** [comment]
@dbarbier why do you think we'll need to overload OptimProblem ?

**Comment by sofianehaddad** [comment]
@jschueller @dbarbier Maybe in the framework of robust optimization, it will be important to have a specific class which inherits from OptimizationProblem. What do you think?

**Comment by jschueller** [comment]
@sofianehaddad I'm not sure what you're referring to

**Comment by jschueller** [comment]
I removed the last commit, leaving for later.

**Comment by dbarbier** [comment]
Thanks, +1

**Pull request merged**
