### PR TITLE
Update use_case_wingweight.rst

### PR DESCRIPTION
**Pull request by m-balesdent**
Correction of Latex typos on wingweight.

### CODE REVIEW

**Review by josephmure — APPROVED** [review]

**Comment by regislebrun** [comment]
I used this use-case in a presentation on sensitivity analysis with OT. I had some questions on it:
* would it be possible to use \ell instead of l in the formula? IMO It makes it easier to read.
* I don't see how the conclusions regarding the effect of the input variables on the weight can be drawn from the cross-cuts. For example, the (l, \Lambda) plot shows an evolution of the weight wrt both variables
* the computation of the Sobol indices based on a chaos expansion shows all the ugly guts of the chaos. Maybe a first run using the user-friendly interface:
```
sizePCE = 800
inputDesignPCE = m.distributionX.getSample(sizePCE)
outputDesignPCE = m.model(inputDesignPCE)

algo = ot.FunctionalChaosAlgorithm(
    inputDesignPCE, outputDesignPCE, m.distributionX)

algo.run()
result = algo.getResult()
print(result.getResiduals())
print(result.getRelativeErrors())
```
would convince the user that it is easy to use, then the detailed interface is used in order to show that, with some tuning of the parameters, the same results are obtained with 200 runs instead of 800 runs.
* an additional comment could be made after the chaos expansion: as the most important variables acts only through decoupled first degree contributions, the hypothesis of a linear dependence between the input variables and the weight is legitimate, which explains why both SRC^2 and Taylor give the exact same results even if the first one is based on a L^2 linear approximation and the second one is based on a linear expansion around the mean value of the input variables.

**Review by regislebrun — CHANGES_REQUESTED** [review]
See my remarks in the main thread.

**Comment by m-balesdent** [comment]
Hello,

>     * I don't see how the conclusions regarding the effect of the input variables on the weight can be drawn from the cross-cuts. For example, the (l, \Lambda) plot shows an evolution of the weight wrt both variables

This graph is just used to preliminary understand the behavior of this dimensional function with respect to the inputs.

>     * the computation of the Sobol indices based on a chaos expansion shows all the ugly guts of the chaos. Maybe a first run using the user-friendly interface:

You're right. The default tuning of chaos expansion  works well on this case.

>     * an additional comment could be made after the chaos expansion: as the most important variables acts only through decoupled first degree contributions, the hypothesis of a linear dependence between the input variables and the weight is legitimate, which explains why both SRC^2 and Taylor give the exact same results even if the first one is based on a L^2 linear approximation and the second one is based on a linear expansion around the mean value of the input variables.

This is now added in the example.

The PR #2150 implements your remarks.

**Comment by jschueller** [comment]
could you put everything in the same PR ? either that one or the other, and close one

**Pull request closed without merging**
