### PR TITLE
Rewrite singleton classes Catalog, Log, ResourceMap and TBB

### PR DESCRIPTION
**Pull request by dbarbier**
Singletons are challenging in C++, it is very hard to have a thread-safe implementation which takes into account dependencies between singletons.

Current code does not work as expected, we had issues on Windows when loading an Excel plug-in because ResourceMap was not initialized. Current code is difficult to read and debug, mostly because singleton builders (`*_init` structs defined along singletons) are initialized in header files and thus duplicated in each object file.

We propose here a simpler pattern: a `MutexLockSingleton` template class is declared in `MutexLock.hxx`, it is modelled after `ResourceMapInstance`. `Catalog`, `Log`, `ResourceMap` and `TBB` are rewritten to use it. 

A static builder is defined in implementation files, and a second one in `GetInstance()`.  There are no threading issues because static variables are instantiated during library load, before user code.  The second builder ensures that initialization order does not matter.

It is not clear whether problems reported above are fixed by this commit, but at least it should be simpler to follow singleton constructions.

### CODE REVIEW

**Comment by dbarbier** [comment]
This pull request superseeds #22.

**Comment by dbarbier** [comment]
Rebased, slightly edited 8447fd9 and added e40245a.

**Comment by jschueller** [comment]
Just tested on mingw with the isolated dlls and a single .exe ; it does work even with a missing config.
+1

**Comment by dbarbier** [comment]
Done, last commit amended.

**Comment by jschueller** [comment]
@dbarbier, it breaks the (mingw) build on windows (not wine).
ResourceMap_init::~ResourceMap_init and Catalog_init::~Catalog_init are called twice when the library is unloaded, and the second call to pthread_mutex_destroy results in a crash.
if I comment them the program exits fine:
```
//  pthread_mutex_destroy( &ResourceMap_InstanceMutex_ );
```

**Pull request merged**
