### PR TITLE
Allowed to build MaximumLikelihoodFactory using a distribution

### PR DESCRIPTION
**Pull request by regislebrun**
Most of the interest of the MaximumLikelihoodFactory is to have a generic factory for distributions with no specific factory. In the previous implementation, this class was only an helper class to ease the work of the C++ programmer to implement its factory, now it can be used out of the box by a Python user.

### CODE REVIEW

**Comment by jschueller** [comment]
What about removing the constructor from a factory ?

**Comment by regislebrun** [comment]
ok.

**Comment by jschueller** [comment]
+1

**Comment by sofianehaddad** [comment]
+1

**Comment by dbarbier** [comment]
+1

**Pull request merged**
