### PR TITLE
Standardize nan/inf serialization

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
@dbarbier are you aware of this kind of problems on msvc with inf/nans ?

**Comment by dbarbier** [comment]
@jschueller No, but it is unclear to me where the problem is; you should add a similar test in C++, maybe this comes from Python?

**Comment by regislebrun** [comment]
I am not sure that this case is specified by the norm (I don't have access to the official document, not free). If it is not, you can expect almost anything, which seems to be the case...

**Comment by dbarbier** [comment]
In fact, it is a very bad idea to check output in this case, AFAICT we do not know how NaNs are printed.  Thus output should be removed, and isnan/isinf (also available in Python from math module) used instead to check value.

**Comment by jschueller** [comment]
Ok. For now I want to print to get the representation in order to modify the string matching code for msvc. Then I can use assert(str(point)==str(point2)) in the final test.

**Comment by dbarbier** [comment]
Err no, `assert(point==point2)`, but it won't work because of positive and negative inf

**Comment by dbarbier** [comment]
No in fact my suggestion do not work either, isinf/isnan must be used.

**Comment by jschueller** [comment]
Why do you think string comparison of the two points won't work (assert(str(point)==str(point2)))?

**Comment by dbarbier** [comment]
Okay I was unclear; it should work, but it is a bad habit to compare string representation.  If you want to check that something is inf or nan, it is better to use isinf/isnan IMO.

**Comment by regislebrun** [comment]
BTW there are SpecFunc::IsNaN() and SpecFunc::IsInf() for this purpose ;-)

**Comment by jschueller** [comment]
Yes, that's a lot more reasonable!

**Comment by dbarbier** [comment]
Yes, looks much better this way.  We specialize fromStringConverter for Bool, so maybe we will have to do the same for toStringConverter, autobuilders will tell.

**Comment by dbarbier** [comment]
They make sense for all numeric types

**Comment by jschueller** [comment]
I think we're there, updated my commit:

```
Standardize nan/inf serialization

The string representation of nan or inf values varies across compilers,
for example gcc: nan/inf, vc<14: 1.#QNAN, 1.#IND, 1.#INF etc.

Now when we detect nan/inf using SpecFunc primitives and serialize it as "nan", "inf" of "-inf".
The tests are updated accordingly.
```

**Comment by dbarbier** [comment]
Tests are not accurate enough IMO, you should print output of the 3 functions IsInf, IsNaN and IsNormal, to make sure that values keep their semantics after write+read.  This does not preserve negative NaNs, but this does not make sense, so there is no problem.  Otherwise it looks good to me.

**Comment by jschueller** [comment]
Ok, updated.

**Comment by regislebrun** [comment]
+1

**Pull request merged**
