### PR TITLE
[RFC] Transpose CovarianceModelImplementation::partialGradient

### PR DESCRIPTION
**Pull request by dbarbier**
It is more logical to have elements transposed.  See for instance TensorizedCovarianceModel::partialGradient.

### CODE REVIEW

**Comment by dbarbier** [comment]
In fact all gradients should be transposed to speed-up computations.  Is it okay to proceed?

**Comment by regislebrun** [comment]
ok for me!

**Comment by jschueller** [comment]
ok

**Comment by dbarbier** [comment]
It is too much work to transpose all gradients.  I am closing this PR for now, and will get back to it later.

**Pull request closed without merging**
