### PR TITLE
Add SpecFunc::BinomialCoefficient

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
I mostly needed the integer number of combinations ; do you think it's ok to add UInt SpecFunc::Combinations(n,k) that calls BinomialCoefficient(n,k) and throws if overflow ?

**Comment by regislebrun** [comment]
Only the integer version seems to be needed, so BinomialCoefficient should return an integer. In order to get an accurate value, one should think about performing only integer arithmetic, I am not 10% sure that the rounded floating point computation is accurate enough for large arguments. Have a look here:
http://stackoverflow.com/questions/11032781/fastest-way-to-generate-binomial-coefficients

**Comment by jschueller** [comment]
Depends if large is greater than the integer range.
Anyway integer computation is much cheaper for our needs.

**Comment by regislebrun** [comment]
+1

**Pull request merged**
