### PR TITLE
Dirac covariance model

### PR DESCRIPTION
**Pull request by sofianehaddad**
The following PR, similar to #55   adds the Dirac covariance model.
Also, some new methods (discretizeHMatrix, discretizeAndFactorizeHMatrix) are added to CovarianceModel classes

### CODE REVIEW

**Comment by jschueller** [comment]
Looks very good, I only could spot some tiny details.

**Comment by jschueller** [comment]
setParameters was not renamed in #50, I should have seen it sooner.

**Comment by sofianehaddad** [comment]
@jschueller thank you for your feedback
For the initialization of scalar, it has already been fixed in d976eff
Otherwise, I will fix space/Numerical precision in tests 
For setParameter, I should have fail a rebase because I ve done it. I will open a new PR

**Comment by sofianehaddad** [comment]
@jschueller thank you for your feedback
Changes have been done
The covariance model implements a setParameter class, so it can be merged after #66

**Comment by jschueller** [comment]
ok, thanks

**Comment by regislebrun** [comment]
+1

**Comment by jschueller** [comment]
HMatrixParameters.hxx is not installed:
http://autobuilder.openturns.org/openturns/pull/65/module/ottemplate/commit/2ef835c064028ab68c8aa11a59358b82c4f85bb3/squeeze-x86_64-module-linux/distcheck-launcher.log

**Comment by sofianehaddad** [comment]
@jschueller strange, have a look at 04f81d5

**Comment by jschueller** [comment]
yeah you installed the .cxx : ]

**Comment by sofianehaddad** [comment]
Fixed, thank you

**Comment by jschueller** [comment]
It's now stated that there are conflicts, maybe it needs a rebase ?

**Comment by sofianehaddad** [comment]
@jschueller fixed

**Comment by dbarbier** [comment]
+1

**Pull request merged**
