### PR TITLE
Fix PlotDesign

### PR DESCRIPTION
**Pull request by sofianehaddad**
For dimension > 2, the PlotDesign should revert x & y axes

### CODE REVIEW

**Comment by jschueller** [comment]
did you enable circleci on your repo ?

**Comment by sofianehaddad** [comment]
@jschueller yes why ?

**Comment by jschueller** [comment]
I was wondering if the failed result of circleci was the job run from your repo instead of the pr here.

**Comment by sofianehaddad** [comment]
ah ok. The url seems to be linked to my repo

**Pull request merged**
