### PR TITLE
Release 1.11

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by regislebrun** [comment]
+1

**Comment by dbarbier** [comment]
-1, I do not understand your merges, this branch is based on master and contains all PRs.

**Comment by jschueller** [comment]
@dbarbier, i'll cherry-pick the commits here to the branch 1.11, then I'll change the version only in 1.11.

Branch 1.11 contains fixes, plus commits from #769, and also some warning fixes

**Comment by jschueller** [comment]
Yes, I was about to backport these PRs. No more warnings fixes.

**Pull request merged**
