### PR TITLE
Encapsulate muParser

### PR DESCRIPTION
**Pull request by jschueller**
Allows to compile without muParser headers
See http://trac.openturns.org/ticket/727

Also abstracts the parser idea so no more muparser-specific code in
AnalyticalNumericalMath(Evaluation|Gradient|Hessian)Implementation.cxx

### CODE REVIEW

**Comment by dbarbier** [comment]
+1, but new naming is confusing IMO, AnalyticalParser inherits from mu::Parser, and by reading MuParser.hxx, it is quite hard to see why it is named like this.  IMO it is better to swap AnalyticalParser and MuParser names.

**Comment by jschueller** [comment]
Agreed

**Comment by jschueller** [comment]
@dbarbier, ok removed

**Comment by dbarbier** [comment]
+1, thanks

**Comment by regislebrun** [comment]
+1

**Pull request merged**
