### PR TITLE
Karhunen loeve factory

### PR DESCRIPTION
**Pull request by regislebrun**
The documentation will come in a separate PR.

### CODE REVIEW

**Comment by jschueller** [comment]
Why a separate PR for the doc ?

**Comment by regislebrun** [comment]
Because someone else was willing to write it ;-)! In fact it will be part of this PR.

**Comment by jschueller** [comment]
Ok, we will wait for the doc to land before review then.

**Comment by jschueller** [comment]
cppcheck_KarhunenLoeveP1Factory_std fails:
http://autobuilder.openturns.org/openturns/pull/103/squeeze-x86_64-ot-linux/LastTest.log

**Comment by jschueller** [comment]
+1

**Pull request merged**
