### PR TITLE
Remove Sample Scalar translation operators

### PR DESCRIPTION
**Pull request by jschueller**
Removes Sample::operator+/-[=](Scalar) for consistency with other objects.

### CODE REVIEW

**Comment by sofianehaddad** [comment]
@jschueller why ? For consistency, we can overload other objects ?

**Comment by jschueller** [comment]
I'm not sure if we should allow it, I mean what the meaning of scalar+matrix, that's not part of the algebra.

**Comment by sofianehaddad** [comment]
@jschueller scalar + Matrix --> Matrix, scalar + CovarianceMatrix --> SymmetricMatrix
IMHO, for the easy use, we should keep the translation operators

**Comment by dbarbier** [comment]
There are other issues:
 * Sample.add and Sample.operator+ have different meanings, which is very confusing
 * Sample.operator+(Point) does not make more sense than with a Scalar
 * Matrix has no in-place operator

On the other hand, we could state that operations with Scalar are performed element-wise for any scalar container, like numpy.

**Comment by jschueller** [comment]
Solution doesn't seems obvious, leaving this for later, at next CT ?

**Pull request closed without merging**
