### PR TITLE
Fix pr657 glitches

### PR DESCRIPTION
**Pull request by regislebrun**
Removed warnings on shadowed variables, added missing entries in openturns.conf and fixed unused function. Sorry.

### CODE REVIEW

**Comment by regislebrun** [comment]
@dbarbier The code looks good and I suspect a bug in matplotlib, as the R output is fine. The use of isVisible() is deactivated by default, but I found sad to throw away good code because of the graphical backend troubles...

**Comment by dbarbier** [comment]
> The use of isVisible() is deactivated by default

It is not, isVisible() is always called.

**Comment by dbarbier** [comment]
I was wrong, but isInnerFace() is also not called by default, IMO it should.

**Comment by regislebrun** [comment]
@dbarbier There is a typo in openturns.conf.in, Mesh-BackfaceCulling was false in ResourceMap and true in openturns.conf.in. I just fixed it. Otherwise, the test to check if a given face has to be drawn is correct. Either backfaceCulling is false, and isVisible is not evaluated because || is true, and the face is selected only if it is not an inner face, or backfaceCulling is true, so isVisible is evaluated and if it is true, then || is true and the face is selected only if it is not an inner face.

**Comment by dbarbier** [comment]
@regislebrun Your code is equivalent to
```
  if ((!backfaceCulling) || (isVisible(visuVertex0, visuVertex1, visuVertex2) && !isInnerFace(simplicesVertex0, simplicesVertex1, simplicesVertex2)))
```

**Comment by regislebrun** [comment]
@dbarbier Thanks for the explanation. I was thinking that the negation operator had a greater priority than || and &&, but that || and && had the same priority, with a left to right evaluation order. I added enough parentheses to make things as clear as an old lisp macro in emacs ;-)!

**Comment by dbarbier** [comment]
Okay, looks good now.

**Pull request merged**
