### PR TITLE
New linear model test

### PR DESCRIPTION
**Pull request by adumasphi**
For the ByPass project, I implemented 3 linear model test to check the homoskedasticity of the residuals (Breusch-Pagan and Harrison-McCabe) and to check the autocorrelation (Durbin-Watson).

All codes are adapted from the R code found in the package "lmtest": _bptest_, _hmctest_ and _dwtest_. The docstrings for all tests are also written.

### CODE REVIEW

**Comment by jschueller** [comment]
@adumasphi, Not bad for a first!
Once you've taken into account all Régis remarks on the code, I suggest you squash commits related to each test together (like a2398c3, 87f6755 and b41c724) it will be easier to review.

**Comment by adumasphi** [comment]
Thanks for your remarks, I included all of them in the update of the commits.
About Durbin Watson, I was able to simplify the algebra and then removing several matrices.

**Comment by jschueller** [comment]
- you should update lib/etc/openturns.conf.in too for resourcemap values
- you can add an entry in the ChangeLog file to mention these new developments

**Comment by adumasphi** [comment]
- Changed in Durbin Watson done
- update openturns.conf.in
- Entries in the ChangeLog done

**Comment by jschueller** [comment]
- Commit message of c092aab is too long, dont mention the files
- As it's a new feature, I didnt expect to be listed in API changes:
```
=== Miscellaneous ===
 * HarrisonMcCabe, BreuschPagan and DurbinWatson tests to test homoskedasticity, autocorrelation of linear regression residuals 
```

**Comment by jschueller** [comment]
+1

**Comment by regislebrun** [comment]
+1

**Comment by adumasphi** [comment]
:smiley:

**Pull request merged**
