### PR TITLE
More efficient characteristic function for the LogUniform distribution

### PR DESCRIPTION
**Pull request by regislebrun**
I implemented the complex Exponential Integral function into the SpecFunc class, which allows to evaluate the characteristic function of the LogUniform distribution in an efficient way. It improves the arithmetic of distributions in terms of speed and accuracy.

### CODE REVIEW

**Comment by jschueller** [comment]
- A SpecFunc::Ei entry in SpecFunc_doc.i.in should be added
- Because of the whitespace changes in t_LogUniform_std.cxx, we do not see what changed, you could revert it and modify just the relevant lines

**Comment by jschueller** [comment]
```
1 - distcheck FAILED for openturns/openturns squeeze x86_64 -ot-linux
Full logs can be seen there http://autobuilder.openturns.org/openturns/pull/37/squeeze-x86_64-ot-linux/ , last 20 lines:
Scanning dependencies of target t_MaximumEntropyOrderStatisticsCopula_std
[ 78%] Building CXX object lib/test/CMakeFiles/t_MaximumEntropyOrderStatisticsCopula_std.dir/t_MaximumEntropyOrderStatisticsCopula_std.cxx.o
Linking CXX executable t_LogNormalFactory_std
[ 78%] Built target t_LogNormalFactory_std
Scanning dependencies of target t_MultinomialFactory_std
[ 78%] /home/openturns/distcheck/workdir/lib/test/t_LogUniform_std.cxx: In function ‘int main(int, char**)’:
/home/openturns/distcheck/workdir/lib/test/t_LogUniform_std.cxx:112: error: redeclaration of ‘OT::NumericalComplex CF’
```

**Comment by regislebrun** [comment]
Hopefully fixed all the issues. Added docstring/sphinx documentation plus a validation script.

**Comment by jschueller** [comment]
Something went wrong with your history.

**Comment by regislebrun** [comment]
Fixed history mess

**Comment by jschueller** [comment]
+1

**Comment by dbarbier** [comment]
+1

**Pull request merged**
