### PR TITLE
Fix RandomMixture::computePDF with 2 atoms

### PR DESCRIPTION
**Pull request by sofianehaddad**
This fix http://trac.openturns.org/ticket/887 : the kernel convolution should be performed only if all atoms are continuous.

Fix also a small bug in RandomMixture::isIntegral

### CODE REVIEW

**Comment by jschueller** [comment]
the ticket must be listed in the changelog

**Comment by sofianehaddad** [comment]
@jschueller you are right, thanks
In the 1.9 section or current Bug fixes ?

**Comment by jschueller** [comment]
in the 1.9 section as I'll backport it

**Comment by regislebrun** [comment]
-1 a RandomMixture is continuous as soon as one of the atoms is continuous. The bug is elsewhere (the use of a numerical convolution when there are 2 atoms without checking that both atoms are continuous). I have a fix on my laptop with no way to commit it before next week.

**Comment by sofianehaddad** [comment]
@regislebrun agreed that RM is continuous as soon as one of the atoms is continuous.
That is why we check that **both the two atoms should be continuous** in order to use the convolution

**Comment by regislebrun** [comment]
+1 I have also implemented a simplification mechanism to deal with the sum of discrete atoms (resulting into a unique discrete atom) and a discrete and a continuous atom (leading to a Mixture atom). This PR is related to the PR concerning getSupport() as we have to deal with the potential huge number of points in the support, thus in the resulting unique discrete distribution or the number of atoms in the Mixture.

**Pull request merged**
