### PR TITLE
Big sample2

### PR DESCRIPTION
**Pull request by jschueller**
see #9

### CODE REVIEW

**Comment by dbarbier** [comment]
+1, thanks for updating.
Looks good to me, but please keep it open for several days so that other developers have a chance to give their opinion.

**Comment by jschueller** [comment]
@dbarbier Ok, no problem.

**Comment by jschueller** [comment]
I don't think much can be reused, besides ordering is different for matrices.

**Comment by regislebrun** [comment]
I was thinking about separating the computation of the optimal column width, the decorations (descriptions, row number) and the printing of the raw values with the potential ellipsis. But you are right: the data layount is different between the two objects and it seems to be difficult to reuse this last part.

**Comment by jschueller** [comment]
@regislebrun Now the computation of the optimal width takes the ellipsis into account and the code should be faster, is that what you were thinking ?

**Comment by jschueller** [comment]
@regislebrun so, good so far ? Can I merge this next week ?

**Pull request merged**
