### PR TITLE
Kriging bugfix

### LINKED ISSUE #1759: Kriging model with StationaryFunctionalCovarianceModel might provide bad results
Hi

We might face issues when using especially `SymbolicFunction`
Here is a small example:
```
import openturns as ot

def computeQ2(y, yhat):
    return 1 - (y - yhat).computeRawMoment(2)[0] / y.computeVariance()[0]

inputDimension = 2

levels = [6, 3]
box = ot.Box(levels)
inputSample = box.generate()
inputSample *= 10.0

model = ot.SymbolicFunction(['x', 'y'], ['cos(0.5*x) + sin(y)'])
outputSample = model(inputSample)

# Validation
sampleSize = 10
inputValidSample = ot.ComposedDistribution(
    2 * [ot.Uniform(0, 10.0)]).getSample(sampleSize)
outputValidSample = model(inputValidSample)

# Basis definition
basis = ot.LinearBasisFactory(inputDimension).build()

rho = ot.SymbolicFunction(
    ['x', 'y'], ['exp(-0.5* (x * x + y * y))'])
covarianceModel = ot.StationaryFunctionalCovarianceModel([5, 2], [1], rho)
covarianceModel.setParameter([6.73119, 3.49911, 4.81502])

# Kriging algorithm
algo = ot.KrigingAlgorithm(inputSample, outputSample, covarianceModel, basis)
algo.setOptimizeParameters(False)
algo.run()
result = algo.getResult()
metaModel = result.getMetaModel()
# Brut eval
outDataTBB = metaModel(inputValidSample)
# Eval by disabling TBB
ot.TBB.Disable()
outDataNoTBB = metaModel(inputValidSample)

print(result.getCovarianceModel().getFullParameter())

print("TBB enabled, Q2=", computeQ2(outputValidSample, outDataTBB))
print("TBB disabled, Q2=", computeQ2(outputValidSample, outDataNoTBB))
```

### PR DESCRIPTION
**Pull request by sofianehaddad**
Fix #1759

### CODE REVIEW

**Comment by sofianehaddad** [comment]
@jschueller could you have a deep look at 4125a77 and 7f74a20 ?

**Review by jschueller — APPROVED** [review]

**Comment by jschueller** [comment]
everything ok, I'd like squashed commits
ignore the mingw error

**Comment by sofianehaddad** [comment]
@jschueller ok. I will try also to fix later `travis`...
The idea was first to see if everything is ok thus I have several commits
Now you approved I will squash commits

**Comment by sofianehaddad** [comment]
@jschueller Small changes are coming. 
`ParallelForCondition` --> `ParallelForIf`, `ParallelReduceCondition` --> `ParallelReduceIf`. Agreed?

**Comment by jschueller** [comment]
yes!

**Review by regislebrun — APPROVED** [review]
Nice job!

**Pull request merged**
