### PR TITLE
Release 1.10

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by dbarbier** [comment]
@jschueller I just noticed https://wiki.debian.org/AutomaticDebugPackages and would like to get rid of libopenturns*-dbg Debian binary package, which is really huge and takes a lot of time to upload.  If you are okay with this proposal, I can make these changes.

**Comment by jschueller** [comment]
Yes, its huge for me too when I have to transfer it from opensuse server to our mirror. Do you want to make the changes here or on the debian git ?

**Comment by jschueller** [comment]
Note that I have to maintain compatibilty with debhelper 8 on my end, and that I patch the control section to "debhelper (>= 8)".

**Comment by dbarbier** [comment]
I do not have access to debian git just now, have pushed a commit on my github repo.  Will test it tonight.  It is not clear to me if we have to implement the transition mentioned in above URL, and since it relies on debhelper 9, I chose to not implement it.

**Comment by jschueller** [comment]
Dope! I'm testing it too now.

**Comment by jschueller** [comment]
Maybe we can change the CMAKE_BUILD_TYPE to Release ?

**Comment by jschueller** [comment]
Should I remove the libopenturns0.11-dbg.install file, or will it be used by the new automatic process ?

**Comment by dbarbier** [comment]
Ah yes, libopenturns0.11-dbg.install should be removed.  I will try to move libOT*-gdb.py elsewhere, but I guess that nobody uses it, so it is not a real problem IMO.

**Comment by jschueller** [comment]
It's building fine for me on all debian/ubuntu versions.

**Comment by jschueller** [comment]
@dbarbier a debug package is built, from debian 9: libopenturns0.11-dbgsym_1.10-1_amd64.deb
https://download.opensuse.org/repositories/science:/openturns/Debian_9.0/amd64/

**Pull request merged**
