### PR TITLE
Better use of CovarianceModelCollection

### PR DESCRIPTION
**Pull request by sofianehaddad**
The PR fixes http://trac.openturns.org/ticket/841

### CODE REVIEW

**Comment by regislebrun** [comment]
+1

**Comment by jschueller** [comment]
nice, I did a similar patch while in the train for this, but using the macros:
https://github.com/jschueller/openturns/commit/7b9395820fa329e3fbe77ebb4d466535a32f6ff9

**Comment by sofianehaddad** [comment]
@jschueller looks great. Did not know about the macros

**Comment by jschueller** [comment]
I opened #260

**Comment by sofianehaddad** [comment]
@jschueller ouch I was fixing the CovarianceModel.i by using your tip...

**Comment by jschueller** [comment]
@sofianehaddad, oh sorry, I'll close mine

**Comment by sofianehaddad** [comment]
@jschueller you are right for the PyObject* constructor but extra constructor with other arguments is not supported ( TensorizedCovModel(PyObject*, NP &)  for example)

**Comment by jschueller** [comment]
If TensorizedCovarianceModel(const CovarianceModelCollection & collection) works with a list of cov model, then TensorizedCovarianceModel(const CovarianceModelCollection & collection, const NumericalPoint & scale) should work too.

**Comment by sofianehaddad** [comment]
strange because one moment I had TCM([cov1,cov2]) ok but TCM([cov1;cov2], [1,2]) nok
It seems now to be fixed, thanks

**Comment by jschueller** [comment]
+1

**Pull request merged**
