### PR TITLE
Change behavior of NumericalSampleImplementation::sort

### PR DESCRIPTION
**Pull request by dbarbier**
After a container is being sorted, one can assume that
   c[i] <= c[j] for all i <= j
Previous implementation was breaking this assumption.  This fixes trac#824.

Also add a NS::unique() method to sort a NS and remove duplicated points.

### CODE REVIEW

**Comment by jschueller** [comment]
+1

**Comment by regislebrun** [comment]
+1

**Comment by jschueller** [comment]
you can mention in the changelog that it closes http://trac.openturns.org/ticket/824

**Comment by dbarbier** [comment]
I had to rename unique() into sortUnique() because this definition shadows Pointer::unique().

**Comment by jschueller** [comment]
+1

**Comment by regislebrun** [comment]
+1

**Pull request merged**
