### PR TITLE
Parametrize statistical tests by first kind risk

### PR DESCRIPTION
**Pull request by jschueller**
... instead of 1-risk

follow-up of #812

### CODE REVIEW

**Comment by jschueller** [comment]
I noticed that in the R2 tests (LinearModelRSquared, LinearModelAdjustedRSquared) the threshold is still the r2, not the risk level.

**Comment by regislebrun** [comment]
@jschueller What is the rational behind this choice for R2 tests?

**Comment by jschueller** [comment]
Hum... the definition of the P-value must be changed.

**Comment by sofianehaddad** [comment]
What about fitting tests ?

**Comment by regislebrun** [comment]
@jschueller I rewrote the documentation of TestResult in a commit related to PR#812 with the definition of the p-value&co, but I had to drop it in order to speed-up the integration process of the PR. From my point of view, the current TestResult class is a little bit dumb as it does not include the value of the test statistics nor the associated threshold, so you don't have any room to store the value of the test statistics...

**Comment by jschueller** [comment]
@sofianehaddad, changed missing FittingTest too

**Comment by jschueller** [comment]
Should I drop the 2nd commit ?

**Comment by jschueller** [comment]
I dropped the last commit, the linear model test result is unchanged.

**Comment by sofianehaddad** [comment]
IMO we should remove the stat test associated to LinearModel as we are just comparing `R2` to a specific threshold

Otherwise seems ok for me, +1

**Comment by jschueller** [comment]
I can deprecate it.

**Comment by regislebrun** [comment]
+1

**Pull request merged**
