### PR TITLE
Embed notebook in sphinx doc

### PR DESCRIPTION
**Pull request by jschueller**
This allows to embed notebooks in the sphinx doc using nbsphinx (http://nbsphinx.rtfd.io/).
I chose to not render notebooks when building the doc, they are tested with t_notebook.py.
For discussion, more on this on february 9.

### CODE REVIEW

**Comment by jschueller** [comment]
@dbarbier I restored the travis script

**Comment by sofianehaddad** [comment]
@jschueller maybe fa084e5 should be in a separate PR?

**Comment by jschueller** [comment]
@sofianehaddad if you want

**Comment by sofianehaddad** [comment]
@jschueller could we do the same thing for t_notebook as for t_docstring? I mean split the tests
Examples will be added gradually so in order to keep time < timeout and for easy debugging it could be better. What do you think?

**Comment by jschueller** [comment]
Yes, absolutely, maybe later when we have more notebooks and then we could decide on how to split them.

**Comment by sofianehaddad** [comment]
ok

**Comment by regislebrun** [comment]
+1

**Pull request merged**
