### PR TITLE
DistributionFactory

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by dbarbier** [comment]
.

**Comment by sofianehaddad** [comment]
I think that the PR should be splitted into two distinct PR because 750dbed fixes docstring whereas e20e46a implies more changes and feedback

BTW, I agree with the two commits so it's +1 for me

**Comment by regislebrun** [comment]
+1

**Comment by jschueller** [comment]
ok i'll do the rename in a separate pr

**Pull request merged**
