### PR TITLE
Covariance model enhancements

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by regislebrun** [comment]
+1

**Comment by jschueller** [comment]
@sofianehaddad the matrix returned is symmetric, so it does not affect other computations doesn't it ?

**Comment by jschueller** [comment]
@sofianehaddad unfortunately I wont have time to go further for the gradients, would it be okay to include it as is, or should I thrash this ?

**Comment by sofianehaddad** [comment]
oki for me

**Pull request merged**
