### PR TITLE
Update NAIS.cxx

### PR DESCRIPTION
**Pull request by m-balesdent**
Modification of iteration number to reflect that an initial sampling has been performed. Allows to compute the correct value of OuterSampling.

### CODE REVIEW

**Comment by m-balesdent** [comment]
> that's not consistent with other algos, ie subset where the number of iterations does not take into account the initial doe



But the outer sampling is note correct in this case. Would it be correct to keep iteration number but to replace the outersampling by getMaximumOuterSampling() * (iterationNumber+1) ?

**Comment by jschueller** [comment]
ah, you mean for the result ? yes indeed, this makes sense to count the initial DOE for the evaluation cost

**Comment by m-balesdent** [comment]
> ah, you mean for the result ? yes indeed, this makes sense to count the initial DOE for the evaluation cost

Yes. The same occurs in Cross Entropy.

**Comment by jschueller** [comment]
in subset too then

**Review by jschueller — COMMENTED** [review]
I checked and this is what is done in subset too, so +1

**Review by jschueller — APPROVED** [review]

**Review by sofianehaddad — APPROVED** [review]

**Review by josephmure — APPROVED** [review]

**Pull request merged**
