### PR TITLE
Fix Kriging random failures

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by regislebrun** [comment]
@jschueller I am very surprised by the fact that this simple change works. In the new implementation of KrigingAlgorithm, the parameters of the covariance model are always optimized, so even if you think you have fixed the values of the scale parameter, it is recomputed. A numerical miracle?

**Comment by regislebrun** [comment]
+1

**Comment by jschueller** [comment]
@regislebrun, the tests do not fail anymore, I ran them a few 100s time on 2 different boxes.
tip: ctest has a decidated ```--repeat-until-fail N``` option.

**Comment by regislebrun** [comment]
@jschueller  Ok good news, I was not able to catch it! To merge ASAP ;-)!

**Comment by sofianehaddad** [comment]
+1

**Pull request merged**
