### PR TITLE
Fixed help page for the LogNormal and LogNormalMuSigma classes.

### LINKED ISSUE #1031: The doc for LogNormal and LogNormalMuSigma is confusing
The text inside: 
http://openturns.github.io/openturns/master/user_manual/_generated/openturns.LogNormal.html
and 
http://openturns.github.io/openturns/master/user_manual/_generated/openturns.LogNormalMuSigma.html
is not clear enough about the meaning of the parameters.

Within the LogNormal page, the text: 

muLogfloat : location parameter \mu_\ell.

should be replaced with:

muLogfloat : location parameter \mu_\ell, the expectation of log(X)

Within LogNormalMuSigma, the text 

mufloat: Mean.

should be replaced with:

mufloat: The mean of X.

After the text "The native parameters are defined as follows:" and the equation, we should insert: 

where $\mu_\ell$ (resp. $\sigma_l=\ell$) is the mean of log(X) (resp. the standard deviation of log(X)).

### PR DESCRIPTION
**Pull request by mbaudin47**
Fixes #1031.
The goal of the commit is to clarify the meaning of the mean and sigma parameters, be it for X or log(X).
This is, I hope, a clear PR on a neat git branch.

### CODE REVIEW

**Comment by jschueller** [comment]
please rebase

**Comment by mbaudin47** [comment]
I did not see the conflict: it should be fine now.

**Comment by sofianehaddad** [comment]
@mbaudin47 no conflits but the rebase is strange. 

First update your local master and fix the issue using  an interactive rebase : 

```git rebase -i master fixLNDoc```

And remove the corresponding commit : 

 ``` Merge branch 'master' into fixLNDoc```

**Comment by mbaudin47** [comment]
Thanks for the tip! I think this is good now.

**Comment by sofianehaddad** [comment]
Please solve the conflict

**Comment by mbaudin47** [comment]
This is good to go I hope.

**Comment by sofianehaddad** [comment]
last commit should be removed

**Comment by jschueller** [comment]
see #1079

**Pull request closed without merging**
