### PR TITLE
Add about section

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by regislebrun** [comment]
@jschueller What kind of help is wanted?

**Comment by jschueller** [comment]
What do you think could be added in that section ? Is the history section ok to you ? Do you want to add more informations on authors ? Maybe some of your publications ?

**Comment by sofianehaddad** [comment]
@jschueller : 
 - openturns user days
 - How to cite OT

**Comment by jschueller** [comment]
@sofianehaddad ok, added

**Comment by sofianehaddad** [comment]
I think we could merge it and update it progressively

**Pull request merged**
