### PR TITLE
Fix student factory

### PR DESCRIPTION
**Pull request by regislebrun**
The previous code was completely wrong. Now, the factory is able to estimate multivariate Student distributions, with the restriction of nu>2 due to the use of first and second moments for the location and scale parameters. The correlation is estimated in a robust way using the sample Kendall tau matrix, and the number of degrees of freedom nu is obtained by profiled log-likelihood maximization.

I also improved the elliptical distributions: now the log-PDF is computed directly on a logarithmic scale, improving the accuracy of log-likelihood computations.

### CODE REVIEW

**Comment by jschueller** [comment]
The test slightly fail on mingw though.

**Comment by jschueller** [comment]
The test slightly fail on mingw though, please fix the numerical precision.

**Comment by regislebrun** [comment]
@jschueller done

**Comment by jschueller** [comment]
The python student test fails, seems setnumericalprecision(4) would do it like the cxx test.

**Comment by jschueller** [comment]
The test fails on appveyor, small numeric diff.

**Comment by regislebrun** [comment]
@jschueller I hope this time it will be ok. Otherwise, I will have to remove all the significant figures from the result ;-)!

**Comment by jschueller** [comment]
it's ok now on appveyor, thanks

**Pull request merged**
