### PR TITLE
Multidimensional piecewise linear function

### PR DESCRIPTION
**Pull request by regislebrun**
It is the Karhunen-Loeve companion!

### CODE REVIEW

**Comment by jschueller** [comment]
How about the KarhunenLoeveP1Factory::build commented loop/return problem I told you about,
wasn't supposed to be addressed with this PR ?

```
Basis KarhunenLoeveP1Factory::build(const CovarianceModel & covarianceModel,
                                     NumericalPoint & selectedEV) const
{
   const ProcessSample resultAsProcessSample(buildAsProcessSample(covarianceModel, selectedEV));
   Basis result(0);
   for (UnsignedInteger i = 0; i < resultAsProcessSample.getSize(); ++i)
     //    result.add(P1LagrangeEvaluationImplementation(resultAsProcessSample.getField(i)));
   return result;
}
```

**Comment by regislebrun** [comment]
@jschueller I already had a look at python/src/OrthogonalUniVariatePolynomialFamily.i but I am a bit confused by the exact meaning of numinputs, $1 and *$1. In the case of OrthogonalUniVariatePolynomialFamily there is only one argument and it is the input/output argument. In my case I have 3 arguments and only the last one is an input/output argument.

Concerning the build() method, it should have landed to github. I may have miss something working so late at night...

**Comment by jschueller** [comment]
It is only relative to the current set of parameters wrapped, so you can safely ignore that and copy-paste almost everything.

**Comment by jschueller** [comment]
as for the build() method, I dont see it in that PR

**Comment by jschueller** [comment]
+1

**Comment by jschueller** [comment]
@dbarbier, @sofianehaddad, thoughts on this ? afaic it's ready to go to master

**Comment by sofianehaddad** [comment]
it seems that one part of f4fadc9 has been done in 8214235, thus the two commits should be squashed or split should be done correctly
Otherwise it is ok for me

**Comment by regislebrun** [comment]
@sofianehaddad Ok I squash them. No time to learn how to split things.

**Comment by sofianehaddad** [comment]
+1

**Pull request merged**
