### PR TITLE
Gpd

### PR DESCRIPTION
**Pull request by adutfoy**
@jschueller : I added an example to illustrate the treatment of covariates (Fremantle ex). We find as Coles! :-) 
I also clarified the different options of normalization method and the intial point used to the maximum likelihood algorithm with covariates and time varying.

### CODE REVIEW

**Review by regislebrun — APPROVED** [review]

**Comment by josephmure** [comment]
The following line tries to draw a Curve plotting data with all y values equal to minus infinity.

https://github.com/openturns/openturns/blob/5fe6a05da76e854d4e3b3a153d73d7bdeb8396c4/python/doc/examples/data_analysis/distribution_fitting/plot_estimate_gev_fremantle.py#L646

`print(gridQuantile)` yields (cut for length)

```
drawables=[class=... Curve ...  size=129 dimension=2 data=[[1897,-inf],[1897.72,-inf],[1898.44,-inf],[1899.16,-inf],[1899.88,-inf],[1900.59,-inf],[1901.31,-inf],[1902.03,-inf],[1902.75,-inf],[1903.47,-inf],[1904.19,-inf],[1904.91,-inf],[1905.62,-inf],[1906.34,-inf],[1907.06,-inf],[1907.78,-inf],[1908.5,-inf],[1909.22,-inf],[1909.94,-inf],[1910.66,-inf],[1911.38,-inf],[1912.09,-inf],[1912.81,-inf],[1913.53,-inf],[1914.25,-inf],[1914.97,-inf],[1915.69,-inf],[1916.41,-inf],[1917.12,-inf],[1917.84,-inf],[1918.56,-inf],[1919.28,-inf],[1920,-inf],[1920.72,-inf],[1921.44,-inf],[1922.16,-inf],[1922.88,-inf],[1923.59,-inf],[1924.31,-inf],[1925.03,-inf],[1925.75,-inf],[1926.47,-inf],[1927.19,-inf],[1927.91,-inf],[1928.62,-inf],[1929.34,-inf],[1930.06,-inf],[1930.78,-inf],[1931.5,-inf],[1932.22,-inf],[1932.94,-inf],[1933.66,-inf],[1934.38,-inf],[1935.09,-inf],[1935.81,-inf],[1936.53,-inf],[1937.25,-inf],[1937.97,-inf],[1938.69,-inf],[1939.41,-inf],[1940.12,-inf],[1940.84,-inf],[1941.56,-inf],[1942.28,-inf],[1943,-inf],[1943.72,-inf],[1944.44,-inf],[1945.16,-inf],[1945.88,-inf],[1946.59,-inf],[1947.31,-inf],[1948.03,-inf],[1948.75,-inf],[1949.47,-inf],[1950.19,-inf],[1950.91,-inf],[1951.62,-inf],[1952.34,-inf],[1953.06,-inf],[1953.78,-inf],[1954.5,-inf],[1955.22,-inf],[1955.94,-inf],[1956.66,-inf],[1957.38,-inf],[1958.09,-inf],[1958.81,-inf],[1959.53,-inf],[1960.25,-inf],[1960.97,-inf],[1961.69,-inf],[1962.41,-inf],[1963.12,-inf],[1963.84,-inf],[1964.56,-inf],[1965.28,-inf],[1966,-inf],[1966.72,-inf],[1967.44,-inf],[1968.16,-inf],[1968.88,-inf],[1969.59,-inf],[1970.31,-inf],[1971.03,-inf],[1971.75,-inf],[1972.47,-inf],[1973.19,-inf],[1973.91,-inf],[1974.62,-inf],[1975.34,-inf],[1976.06,-inf],[1976.78,-inf],[1977.5,-inf],[1978.22,-inf],[1978.94,-inf],[1979.66,-inf],[1980.38,-inf],[1981.09,-inf],[1981.81,-inf],[1982.53,-inf],[1983.25,-inf],[1983.97,-inf],[1984.69,-inf],[1985.41,-inf],[1986.12,-inf],[1986.84,-inf],[1987.56,-inf],[1988.28,-inf],[1989,-inf]]
```

**Comment by adutfoy** [comment]
@jschueller : I removed the line ....
It is strange because on my computer, the graph is produced without any problem... It is a bug ion the code?

GrapheQuantile

**Comment by jschueller** [comment]
did your rebuild the library since the update ?

**Comment by adutfoy** [comment]
The problem was that I called drawQuantileFunction1D with a probability level of p=0 instead of p=0.95. I added a check in the function to detect the cases p=0 and p=1 for which the result is +/-inf

**Review by jschueller — APPROVED** [review]

**Review by josephmure — APPROVED** [review]

**Pull request merged**
