### PR TITLE
Centered Sobol estimation 

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by sofianehaddad** [comment]
@jschueller not sure about this. Even if the estimators look better (particularly Mauntz-Kucherenko/Saltelli, which are known to lack efficiency in case of decentered output), the algorithm could not be referenced as MK/Saltelli. ( as you mentioned in http://trac.openturns.org/ticket/786, it becomes another estimator...)

**Comment by regislebrun** [comment]
+1

**Comment by regislebrun** [comment]
@jschueller @sofianehaddad In fact NOBODY excepted us implement this method in its initial form. Either we remove it from the library (there is room for it in a module), or we adopt Julien's patch. I am quite surprised by this patch as I thank it was already done!

**Comment by jschueller** [comment]
@dbarbier some thoughts ?

**Comment by sofianehaddad** [comment]
@jschueller still disagree with the changes. But if you plan to integrate it you must update docstrings as it is not the original methods that are implemented

**Comment by dbarbier** [comment]
+1

**Pull request merged**
