### PR TITLE
Fix long long being only available since c++11

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by dbarbier** [comment]
In general I am reluctant to add #ifdef in header files, there may be trouble if you build OT with a compiler and link against it with a different compiler.  Why not simply drop these definitions?  Long long is not used anywhere in OpenTURNS.

**Comment by jschueller** [comment]
Ok, i'll try to remove them.

**Comment by jschueller** [comment]
Seems it wants (u)int64_t to stream Unsigned64BitsInteger types.

**Comment by dbarbier** [comment]
Indeed; if it causes too much trouble, reintroduce your initial changes.

**Comment by jschueller** [comment]
It's the same issue we had in StorageManager.hxx on osx : unsigned long is the same as uint64, so I have to use the same macro to avoid defining twice the same functions on this platform.

**Comment by regislebrun** [comment]
IMO we should use only types with known size to avoid portability troubles as much as possible. Would it be possible to have only uint64_t, int64_t, uint32_t and int32_t, with SignedInteger and UnsignedInteger aliasing int64_t and uint64_t? Long, int and so on are just painful!

**Pull request merged**
