### PR TITLE
Revert "Add Gibbs example"

### PR DESCRIPTION
**Pull request by mbaudin47**
Reverts openturns/openturns#2028

I did not approve PR #2028, and this is why I open this PR.

### CODE REVIEW

**Review by josephmure — APPROVED** [review]
That is true. I guess we must continue the discussion in the thread of PR #2028 for the time being ?

**Comment by sofianehaddad** [comment]
Ok it was integrated too early. 
But IMHO we should rather make an update of the alreeady integrated code (making a new PR accounting for @mbaudin47 remarks on #2028 )
@josephmure @mbaudin47 who can do it?

**Comment by jschueller** [comment]
I have a new branch dedicated to the doc, I can do it there

**Comment by mbaudin47** [comment]
This PR is a follow-up to the original PR #1985.

**Comment by sofianehaddad** [comment]
see #2081

**Pull request closed without merging**
