### PR TITLE
Fix problems with SWIG binding of ComplexMatrix::solveLinearSystem

### PR DESCRIPTION
**Pull request by dbarbier**
Fixes trac#802.

Not sure why this change is needed though. 
Other *Matrix::solveLinearSystem methods were not affected.

### CODE REVIEW

**Comment by regislebrun** [comment]
+1

**Comment by sofianehaddad** [comment]
Please add notes on the ChangeLog

**Comment by sofianehaddad** [comment]
Could you please add a test that illustrates the problem is solved?

**Comment by jschueller** [comment]
yes please a small test-case, and squash them except 295e73c

**Comment by dbarbier** [comment]
I can't add a test, AFAICT this problem only occurs from an interactive session.

**Comment by jschueller** [comment]
ok

**Pull request merged**
