### PR TITLE
Missing abs in LinearModelTest::LinearModelDurbinWatson

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
cc @adumasphi

**Comment by regislebrun** [comment]
Is there a reference to check if the maths are correct? Looks good but I have no time to dig into my math books to check the formula...

**Comment by jschueller** [comment]
@adumasphi is there a reference for the formula somewhere ?

**Comment by adumasphi** [comment]
Yes, there are references : Testing for Serial Correlation in Least Squares Regression. I, II et III.
DOI : 10.2307/2332391
DOI : 10.2307/2332325
DOI : 10.2307/2334313
I have the papers if you want to read it.

The formulation I have coded is coming from the third paper in which it corresponds with a normal approximation of the computed statistic. In this third paper, Durbin and Watson compare several methods to estimate the p-value. They conclude that this method is accurate enough for common practice. More accurate methods exist such as one using the "pan" algorithm or the Henshaw method.

**Comment by dbarbier** [comment]
I did not read those papers, but approved these changes after checking that the same formula is used in R lmtest package.

**Pull request merged**
