### PR TITLE
Add PythonDistribution parameters accessors

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by dbarbier** [comment]
You could easily implement setParameter method for SciPyDistribution.

**Comment by jschueller** [comment]
How ?

**Comment by dbarbier** [comment]
This should work:
```
    def setParameter(self, args):
        self._dist.args = args
```

**Comment by jschueller** [comment]
Ok, this is totally working.

**Comment by regislebrun** [comment]
+1

**Pull request merged**
