### PR TITLE
Fix some docstrings.

### PR DESCRIPTION
**Pull request by aurelieladier**

### CODE REVIEW

**Comment by jschueller** [comment]
+1

**Comment by sofianehaddad** [comment]
Could you please remove changes in CovarianceModel?
As the model will have new parametrization (cf #50 ) docstrings have already been changed.
Thank you

**Comment by aurelieladier** [comment]
@sofianehaddad ok rebased

**Comment by sofianehaddad** [comment]
+1
thanks

**Comment by regislebrun** [comment]
+1

**Pull request merged**
