### PR TITLE
Taylor doc

### PR DESCRIPTION
**Pull request by adutfoy**
Modified the expression of var(Y) in the general case when the variables may be correlated.

### CODE REVIEW

**Comment by adutfoy** [comment]
@jschueller : There is a problem in the commits... as usual...

**Comment by adutfoy** [comment]
Is there a step-by-step way to fix it DEFINITELY?

**Comment by jschueller** [comment]
yes, you should rebase (git fetch upstream && git rebase upstream/master)
and next time you should start from an up-to-date branch (git fetch upstream && git checkout -b new_branch_name upstream/master):
http://openturns.github.io/openturns/latest/developer_guide/git_workflow.html#keep-your-local-repository-in-sync

**Comment by adutfoy** [comment]
@jschueller : Julien, I really do not understand the problem here..... May you help me? :-)

**Comment by jschueller** [comment]
yes, there was an issue with the new parallel examples generation, one more rebase should fix it

**Review by jschueller — APPROVED** [review]

**Comment by adutfoy** [comment]
@jschueller , @josephmure , @mbaudin47 , @m-balesdent : This PR modifies one formula .... we should merge it now?

**Comment by jschueller** [comment]
ok for me but as many other PRs this one lacks reviewers

**Comment by jschueller** [comment]
lets move it to #2760

**Pull request closed without merging**
