### PR TITLE
Rename covarianceList covarianceModelCollection in HSIC

### LINKED ISSUE #2009: rename HSICEstimator::getCovarianceList
getCovarianceModelCollection

### PR DESCRIPTION
**Pull request by josephmure**
Fix #2009

### CODE REVIEW

**Comment by sofianehaddad** [comment]
I already have a PR


Envoyé depuis Yahoo Mail pour iPhone


Le jeudi, avril 7, 2022, 4:57 PM, Julien Schueller ***@***.***> a écrit :




not covarianceMOdelCollection ?

**Comment by josephmure** [comment]
Yes indeed. Changed to covaranceModelCollection

**Comment by jschueller** [comment]
looks like sofiane is ahead in #2011

**Comment by sofianehaddad** [comment]
@josephmure ChangeLog should be updated

**Comment by jschueller** [comment]
I dont think so, as  hsic was not present in past releases.

**Pull request merged**
