### PR TITLE
Added the computeP1Stiffness() method to the Mesh class. It is mandat…

### PR DESCRIPTION
**Pull request by regislebrun**
…ory to compute eg Karhunen-Loeve expansions of stochastic processes when the modes and the covariance model are approximated using P1 Lagrange finite elements.

### CODE REVIEW

**Comment by sofianehaddad** [comment]
+1

**Comment by jschueller** [comment]
+1

**Comment by dbarbier** [comment]
+1

One very minor note: your commit message should  have a short title, a blank line, then long description, like this: 

```
   Added the computeP1Stiffness() method to the Mesh class

   It is mandatory to compute eg Karhunen-Loeve expansions of
   stochastic processes when the modes and the covariance model
   are approximated using P1 Lagrange finite elements.
```

**Comment by jschueller** [comment]
yes, could you adjust the commit message ?

**Pull request merged**
