### PR TITLE
Document SpecFunc::IsNormal

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
isinf, isnan are already available in math, so add only IsNormal.

**Comment by dbarbier** [comment]
Docstring is wrong, in fact 'IsNormal(x)' is just 'not (isnan(x) || isinf(x))'

**Comment by regislebrun** [comment]
+1

**Comment by regislebrun** [comment]
As SpecFunc.IsNaN() and SpecFunc.IsInf() are visible by the user IMO they should be implemented. BTW, I don't want them to be hidden from the Python interface as it helps a lot in developing Python code that will be later translated into C++.

**Comment by jschueller** [comment]
SpecFunc.IsNaN() and SpecFunc.IsInf() are not exported in the Python interface (they are available in the math module).

**Comment by dbarbier** [comment]
@jschueller In fact IsNaN is exported since there is a typo in SpecFunc.i, but I agree that we should try to avoid function duplicated with math module

**Comment by regislebrun** [comment]
+1

**Pull request merged**
