### PR TITLE
Bipartite graph and CumulativeDistributionNetwork

### PR DESCRIPTION
**Pull request by regislebrun**
It also includes some enhancements of the generic implementation of some methods in DistributionImplementation and CompositeDistribution as a side effect

### CODE REVIEW

**Comment by dbarbier** [comment]
-1, github is unable to display changes in `DistributionImplementation.cxx` because diff is polluted by lots of useless whitespace changes.

**Comment by jschueller** [comment]
Does f540ae4 need to be squashed with other changes (3286a28 ?), we cannot see what happened as the diff is too long.

**Comment by regislebrun** [comment]
Yes they could be merged. I do it ASAP.

**Comment by jschueller** [comment]
BipartiteGraph & CumulativeDistributionNetwork are exposed to Python but have no docstrings, nor tocree entries.

**Comment by dbarbier** [comment]
+1, thanks

**Comment by jschueller** [comment]
+1

**Comment by regislebrun** [comment]
@jschueller Is this PR ok with the autobuilder? I can't get any log...

**Comment by jschueller** [comment]
it's coming this night

**Comment by jschueller** [comment]
only one test fails:
http://autobuilder.openturns.org/openturns/pull/110/squeeze-x86_64-ot-linux/

**Comment by jschueller** [comment]
one digit differs in 32bits:
http://autobuilder.openturns.org/openturns/pull/110/squeeze-i386-ot-linux/distcheck-launcher.log

```
@@ -11,7 +11,7 @@
  [ -0.0044764  0.685993  ]]
 Point=  [1.0, 1.0]
 log pdf =-1.79709e+00
-pdf     =1.65781e-01
+pdf     =1.65780e-01
 cdf     =5.01067e-01
 ccdf    =4.98933e-01
 survival=8.53452e-02
<end of output>
Test time =   1.70 sec
----------------------------------------------------------
Test Failed.
"pyinstallcheck_CumulativeDistributionNetwork_std" end time: Dec 10 16:01 CET
"pyinstallcheck_CumulativeDistributionNetwork_std" time elapsed: 00:00:01
```

**Comment by regislebrun** [comment]
Are they bugs we could solve during the beta phase? I am really busy on two other branches and it takes me a lot of time to fix these tiny glitches. If someone is ready to help, thanks to him.

**Comment by jschueller** [comment]
You're almost there : ) I promess

**Pull request merged**
