### PR TITLE
Enhance matplotlib backend

### PR DESCRIPTION
**Pull request by jschueller**
- Fixes a problem with PolygonArray when colors are defined with names instead of hex codes
- For contours, take account colors, label flag and legend.
- Control image size in pixels

### CODE REVIEW

**Comment by jschueller** [comment]
@regislebrun, to set figure size figure has a default size of 10x10in and the default dpi is 80,(=> 800x800) so you can play with the dpi to get higher resolution with figure_kwargs={'dpi':xx}

**Comment by regislebrun** [comment]
@jschueller It allows to scale the figure, but how to change the aspect ratio? A square figure means a rectangular drawing region, and sometimes one need a square drawing region (and hence a rectangular figure).

**Comment by jschueller** [comment]
You can use the figsize keyword:
```view = View(graph, figure_kwargs={'figsize':(20,10)})```

**Comment by regislebrun** [comment]
@jschueller So natural, compared to view.save('fig.png', 800, 600) ;-)!

**Comment by regislebrun** [comment]
@jschueller So I have to divide the dimensions I would have by 80 and specify the result as the value of figsize? So long since I did my last mental calculation exam...

**Comment by regislebrun** [comment]
+1

**Comment by jschueller** [comment]
@regislebrun I added witdth, height keywords to control image size

**Comment by dbarbier** [comment]
+1

**Pull request merged**
