### PR TITLE
Drop muParser dependency

### PR DESCRIPTION
**Pull request by jschueller**
I dont see a reason to keep it, Exprtk should be faster.

### CODE REVIEW

**Comment by regislebrun** [comment]
Not exactly. On large expressions, exprtk is slower than muparser, and it needs much more memory (leading to crashes in Anatole). Does muparser complexify the packaging of OT, or other reason not yet mentioned?

**Comment by jschueller** [comment]
I had no other reason, ok we keep it for now

**Comment by ArashPartow** [comment]
@regislebrun  

> On large expressions, exprtk is slower than muparser

Can you please provide an example of such an expression? As I'd like to improve ExprTk's evaluation performance wherever possible.

--------

Below are some comparisons taken from:
https://github.com/ArashPartow/math-parser-benchmark-project

Specifically the most recent run: 
https://github.com/ArashPartow/math-parser-benchmark-project/blob/master/logs/shootout_20180421_00.zip

```
Expression 4145 of 6617: "((x+5.123+z*w-x/5.123*z-w-x*5.123*z-w/x+5.123+z*w))"; Progress: #############
[01] ExprTk               (   24.012 ns,       0.519877029103014365, -955856.352909454843029380)
[02] ExprTkFloat          (   35.975 ns,       0.519877195358276367, -955856.442475407849997282)
[03] METL                 (   79.457 ns,       0.519877029103014365, -955856.352909454843029380)
[04] FParser 4.5          (   95.705 ns,       0.519877029103009036, -955856.352909454843029380)
[05] muparser 2.2.4       (  121.846 ns,       0.519877029103014365, -955856.352909454843029380)
[06] muparser 2.2.4 (omp) (  130.157 ns,       0.519877029103014365, -955856.352909454843029380)
[07] MathExpr             (  142.786 ns,       0.519877029103021471, -955856.352909454843029380)
[08] atmsp 1.0.4          (  169.937 ns,       0.519877029103014365, -955856.352909454843029380)
[09] MTParser             (  211.591 ns,       0.519877029103014365, -955856.352909454843029380)
[10] TinyExpr             (  270.268 ns,       0.519877029103014365, -955856.352909454843029380)
[11] Lepton               (  646.458 ns,       0.519877029103014365, -955856.352909454843029380)
[12] muparserx            ( 1042.261 ns,       0.519877029103014365, -955856.352909454843029380)


Expression 4340 of 6617: "(2.2*(3.3*(4.4*(5.5*(((((a-b)+9.9)+8.8)+7.7)+6.6)))))"; Progress: #############
[01] ExprTk               (    5.632 ns,    5604.574800000000323053, 579783600.000244140625000000)
[02] FParser 4.5          (   18.195 ns,    5604.574800000001232547, 579783600.000244140625000000)
[03] METL                 (   54.442 ns,    5604.574800000000323053, 579783600.000244140625000000)
[04] MathExpr             (   64.203 ns,    5604.574800000000323053, 579783600.000244140625000000)
[05] muparser 2.2.4 (omp) (   73.325 ns,    5604.574800000000323053, 579783600.000244140625000000)
[06] muparser 2.2.4       (   73.673 ns,    5604.574800000000323053, 579783600.000244140625000000)
[07] MTParser             (   78.305 ns,    5604.574800000000323053, 579783600.000244140625000000)
[08] atmsp 1.0.4          (   79.159 ns,    5604.574800000000323053, 579783600.000244140625000000)
[09] TinyExpr             (  119.177 ns,    5604.574800000000323053, 579783600.000244140625000000)
[10] Lepton               (  178.924 ns,    5604.574800000000323053, 579783600.000244140625000000)
[11] muparserx            (  560.786 ns,    5604.574800000000323053, 579783600.000244140625000000)
DNQ List
[01] muparserSSE          (    4.811 ns,    5604.574707031250000000, 579783593.750000000000000000)
[02] ExprTkFloat          (    8.159 ns,    5604.574707031250000000, 579783587.676241397857666016)



Expression 4617 of 4759: "(((((((x+y)+(7.123-w))-((x-y)/(7.123*w)))-(((x+y)/(7.123/w))/(x+((y-7.123)/w))))-((((x-y)/(7.123*w))+(x+((y-7.123)*w)))+((x+((y-7.123)/w))*(((x+y)/7.123)-w))))-(((((x*y)-(7.321-w))*(x-(y*(7.321/w))))*((x+(y*(7.321/w)))+(x-((y/7.321)/w))))*(((x-(y*(7.321/w)))-(x-((y/7.321)*w)))-((x-((y/7.321)/w))/(x*(y+(7.321*w))))))))"; Progress: #############
[01] ExprTk               (   98.379 ns,    -177.220728846393768663, -335331788.894636988639831543)
[02] METL                 (  520.099 ns,    -177.220728846393768663, -335331788.894636988639831543)
[03] FParser 4.5          (  531.202 ns,    -177.220728846393740241, -335331788.894636988639831543)
[04] muparser 2.2.4       (  586.636 ns,    -177.220728846393768663, -335331788.894636988639831543)
[05] muparser 2.2.4 (omp) (  605.894 ns,    -177.220728846393768663, -335331788.894636988639831543)
[06] MathExpr             (  684.578 ns,    -177.220728846393768663, -335331788.894636988639831543)
[07] atmsp 1.0.4          (  763.644 ns,    -177.220728846393768663, -335331788.894636988639831543)
[08] TinyExpr             ( 1463.473 ns,    -177.220728846393768663, -335331788.894636988639831543)
[09] MTParser             ( 1891.207 ns,    -177.220728846393768663, -335331788.894636988639831543)
[10] Lepton               ( 2626.112 ns,    -177.220728846393768663, -335331788.894636988639831543)
[11] muparserx            ( 4743.328 ns,    -177.220728846393768663, -335331788.894636988639831543)
DNQ List
[01] muparserSSE          (   64.452 ns,    -177.220825195312500000, -335332040.786743164062500000)
[02] ExprTkFloat          (   96.963 ns,    -177.220703125000000000, -335331737.441724658012390137)




```

**Comment by regislebrun** [comment]
@ArashPartow Hi, I confirm your findings: on small expressions, ExprTk is more efficient than MuParser. But on large ones, at least through the OpenTURNS interface, it is no more true as the following benchmark shows:
- 2000 variables
- a combination of 2000 terms involving the product of 10 variables or functions of a variable
```
import openturns as ot
import openturns.viewer as otv

size = 4000

num_terms = 1000
num_factors = 10
basic_functions = ['', 'exp', 'sin', 'cos', '', '']
num_functions = len(basic_functions)
num_variables = 2000

variables = ['x' + str(i).zfill(len(str(num_variables-1))) for i in range(num_variables)]

formula = ''
for i in range(num_terms):
    if i > 0:
        formula += '+'
    term = ''
    for j in range(num_factors):
        if j > 0:
            term += '*'
        f = basic_functions[ot.RandomGenerator.IntegerGenerate(num_functions)]
        if len(f) > 0:
            term += f + '('
        term += variables[ot.RandomGenerator.IntegerGenerate(num_variables)]
        if len(f) > 0:
            term += ')'
    formula += term
print(formula)
dist = ot.ComposedDistribution([ot.Uniform(1.0, 2.0)]*num_variables)
sample = dist.getSample(size)
from time import time
ts = time()
gr = ot.Graph()
gr.setXTitle("size")
gr.setYTitle("t (s)")
gr.setTitle("ExprTk/MuParser comparison")
gr.setAxes(True)
gr.setGrid(True)
gr.setLegendPosition('topleft')

indices = range(0, size, size // 100)

backends = ["ExprTk", "MuParser"]
reps = 11
for backend in backends:
    ot.ResourceMap.SetAsString('SymbolicParser-Backend', backend)
    data = ot.Sample(len(indices), 2)
    print(backend)
    for i in range(len(indices)):
        num = indices[i]+1
        test = sample[0:num]
        bunch = ot.Sample(reps, 1)
        for j in range(reps):
            t0 = time()
            model = ot.SymbolicFunction(variables, [formula])
            res = model(test)
            t1 = time()
            bunch[j, 0] = t1 - t0
        data[i, 0] = num
        data[i, 1] = bunch.computeQuantilePerComponent(0.5)[0]
        if time() > ts + 5:
            print("i=", i, "t=", t1 - t0, "s")
            ts = time()
        data.exportToCSVFile("timings_" + backend + ".csv")
    gr.add(ot.Curve(data))
gr.setColors(["red", "blue"])
gr.setLegends(backends)
otv.View(gr).save("Comparison.png")
```
For an input of size growing from 1 to 10000, I measure the median time to build the function and evaluate it on this input over 11 reps. It is done using the current master of OpenTURNS, MuParser 2.2.5 and ExprTk a1b1854. It produces the following graph:
Comparison

You can see that ExprTk compiles the expression much faster than MuParser, but evaluates it less efficiently.

**Comment by ArashPartow** [comment]
@regislebrun Thank-you for that analysis. I was wondering would you be able to print some of those randomly generated expressions - especially ones where muparser is faster. I ask because:

1. I would always expect muparser to parse/compile the expression faster than ExprTk - as ExprTk does more optimisation passes
2. For there to be very few _scenarios_ where muparser ends up evaluating faster.

The expressions below are a random selection from:
[https://github.com/ArashPartow/math-parser-benchmark-project/blob/master/logs/shootout_20180421_00.zip?raw=true](https://github.com/ArashPartow/math-parser-benchmark-project/blob/master/logs/shootout_20180421_00.zip?raw=true)

They are comprised of similar components (sin/cos/exp etc) as the ones your testing and are intentionally very large (impractically). 

```
Expression 432 of 440: "tan(sin((1.38/tan(((a/(1.33/sin(((((tan(((((((((e*(((((((3.01-(((tan(cos((cos((tan(tan((((((((cos((a/pi))/pi)-b)+b)-3.72)+a)+e)/b)))/0.60))*a)))-1.28)+1.26)+2.75))-a)/0.27)*pi)/a)-0.13)/3.64))/b)-a)*a)/0.23)+b)-pi)*a))+e)-pi)+b)/b))))+a)))))"; Progress: #############
[01] ExprTk               (  450.269 ns,       0.372935093985997057, 4809727.819923487491905689)
[02] FParser 4.5          (  547.882 ns,       0.372935093985998500, 4809727.819923496805131435)
[03] atmsp 1.0.4          (  644.620 ns,       0.372935093985997057, 4809727.819923496805131435)
[04] MathExpr             (  649.224 ns,       0.372935093985997057, 4809727.819923496805131435)
[05] METL                 (  651.979 ns,       0.372935093985997057, 4809727.819923496805131435)
[06] muparser 2.2.4       (  706.341 ns,       0.372935093985997057, 4809727.819923496805131435)
[07] muparser 2.2.4 (omp) (  707.626 ns,       0.372935093985997057, 4809727.819923496805131435)
[08] TinyExpr             ( 1252.762 ns,       0.372935093985997057, 4809727.819923496805131435)
[09] MTParser             ( 1315.774 ns,       0.372935093985997057, 4809727.819923496805131435)
[10] Lepton               ( 1647.877 ns,       0.372935093985997057, 4809727.819923496805131435)
[11] muparserx            ( 2901.983 ns,       0.372935093985997057, 4809727.819923496805131435)
DNQ List
[01] muparserSSE          (  442.719 ns,       0.372395694255828857, 4809200.614690780639648438)
[02] ExprTkFloat          (  497.121 ns,       0.372704893350601196, 4809958.115220069885253906)

Expression 433 of 440: "cos(tan(tan(tan((((e-(sin((tan((((sin((3.77+((b*((((0.52/((((cos((((((((sin(cos(cos((((a*((((a/((tan((e*0.95))+b)/e))+b)/3.79)/b))+e)/e))))+a)/e)+e)+1.29)*a)*2.28)/1.25))/pi)/0.59)+b)+b))+b)-3.22)*a))*a)))-pi)+b)+0.72))*2.37))+b))/a)*3.87)))))"; Progress: #############
[01] ExprTk               (  444.003 ns,      -0.052376283164872764, -2506769.337559348903596401)
[02] FParser 4.5          (  509.739 ns,      -0.052376283164801807, -2506769.337559064850211143)
[03] METL                 (  512.324 ns,      -0.052376283164872764, -2506769.337559066247195005)
[04] atmsp 1.0.4          (  638.428 ns,      -0.052376283164872764, -2506769.337559066247195005)
[05] MathExpr             (  704.185 ns,      -0.052376283164872764, -2506769.337559066247195005)
[06] muparser 2.2.4       (  727.812 ns,      -0.052376283164872764, -2506769.337559066247195005)
[07] muparser 2.2.4 (omp) (  738.767 ns,      -0.052376283164872764, -2506769.337559066247195005)
[08] MTParser             ( 1228.357 ns,      -0.052376283164872764, -2506769.337559066247195005)
[09] TinyExpr             ( 1260.816 ns,      -0.052376283164872764, -2506769.337559066247195005)
[10] Lepton               ( 1641.715 ns,      -0.052376283164872764, -2506769.337559066247195005)
[11] muparserx            ( 2900.336 ns,      -0.052376283164872764, -2506769.337559066247195005)
DNQ List
[01] muparserSSE          (  433.821 ns,      -0.052292607724666595, -2503133.919090032577514648)
[02] ExprTkFloat          (  496.739 ns,      -0.052292607724666595, -2503133.919090032577514648)

Expression 435 of 440: "(tan((((a+(sin(((((a+((cos((((2.76+(((sin((((((sin((((((cos(cos(cos(((((a/((sin(((((2.83/(((pi/pi)+a)-pi))*0.44)+0.41)+pi))/a)/b))-e)+b)/a))))+pi)+2.28)+b)*a)+b))-pi)*pi)+0.29)/a)*b))+1.87)*pi)/a))/1.59)/pi))+pi)*0.72))*a)*b)+a))+b))-a)+e))-e)"; Progress: #############
[01] ExprTk               (  389.069 ns,      -3.509017821783269930, -56949875.373131796717643738)
[02] FParser 4.5          (  477.641 ns,      -3.509017821783269930, -56949875.373131796717643738)
[03] METL                 (  532.179 ns,      -3.509017821783269930, -56949875.373131796717643738)
[04] atmsp 1.0.4          (  585.080 ns,      -3.509017821783269930, -56949875.373131796717643738)
[05] muparser 2.2.4       (  631.762 ns,      -3.509017821783269930, -56949875.373131796717643738)
[06] MathExpr             (  632.446 ns,      -3.509017821783269930, -56949875.373131796717643738)
[07] muparser 2.2.4 (omp) (  649.633 ns,      -3.509017821783269930, -56949875.373131796717643738)
[08] TinyExpr             ( 1278.221 ns,      -3.509017821783269930, -56949875.373131796717643738)
[09] MTParser             ( 1295.356 ns,      -3.509017821783269930, -56949875.373131796717643738)
[10] Lepton               ( 1712.675 ns,      -3.509017821783269930, -56949875.373131796717643738)
[11] muparserx            ( 2932.263 ns,      -3.509017821783269930, -56949875.373131796717643738)
DNQ List
[01] muparserSSE          (  347.281 ns,      -3.509021043777465820, -56955135.464668273925781250)
[02] ExprTkFloat          (  446.070 ns,      -3.509021043777465820, -56955953.389406204223632813)

Expression 436 of 440: "((a-((cos(cos((a-(((((sin((((a+tan((((e/((((((2.42+((((e*(1.24+((tan(((2.78/(tan((3.53+(a-sin((((((tan((tan(e)+2.11))*b)+a)+a)+pi)*0.78)))))*2.24))-pi))*pi)/pi)))-a)/b)*b))+b)+a)-0.07)/a)+b))+e)*a)))+e)/e))+b)+2.78)*b)+b)+b))))/pi)-0.32))-2.28)"; Progress: #############
[01] muparserSSE          (  317.652 ns,      -1.095613002777099609, -2569432.854652404785156250)
[02] ExprTk               (  379.326 ns,      -1.095613178448014535, -2569435.206692872568964958)
[03] ExprTkFloat          (  420.369 ns,      -1.095613002777099609, -2569432.854652404785156250)
[04] FParser 4.5          (  478.655 ns,      -1.095613178448013425, -2569435.206692872568964958)
[05] METL                 (  558.906 ns,      -1.095613178448013647, -2569435.206692872568964958)
[06] atmsp 1.0.4          (  582.528 ns,      -1.095613178448013647, -2569435.206692872568964958)
[07] muparser 2.2.4       (  644.661 ns,      -1.095613178448013647, -2569435.206692872568964958)
[08] MathExpr             (  645.969 ns,      -1.095613178448013647, -2569435.206692872568964958)
[09] muparser 2.2.4 (omp) (  669.500 ns,      -1.095613178448013647, -2569435.206692872568964958)
[10] MTParser             ( 1227.283 ns,      -1.095613178448013647, -2569435.206692872568964958)
[11] TinyExpr             ( 1251.669 ns,      -1.095613178448013647, -2569435.206692872568964958)
[12] Lepton               ( 1778.642 ns,      -1.095613178448013647, -2569435.206692872568964958)
[13] muparserx            ( 3010.741 ns,      -1.095613178448013647, -2569435.206692872568964958)

Expression 438 of 440: "((0.97-((2.02/(e/((3.84+(sin((sin((((((a*tan(sin(tan((((((b*(a+(((3.30-cos((1.16*sin(cos((cos((((sin((((cos(((cos((tan((cos(b)/e))/e))+a)+b))+e)*3.65)/e))-b)-b)*pi))-b))))))/3.10)/e)))+2.68)-0.68)*1.86)+a)))))/pi)-a)+pi)+a))+b))/pi))*b)))+e))*0.05)"; Progress: #############
[01] ExprTk               (  471.558 ns,      -0.427155342449897557, -1688951.245373840210959315)
[02] muparserSSE          (  535.639 ns,      -0.427155315876007080, -1688950.583338737487792969)
[03] ExprTkFloat          (  552.072 ns,      -0.427155345678329468, -1688950.265702774748206139)
[04] FParser 4.5          (  649.418 ns,      -0.427155342449897557, -1688951.245373840210959315)
[05] atmsp 1.0.4          (  678.762 ns,      -0.427155342449897557, -1688951.245373840210959315)
[06] METL                 (  711.204 ns,      -0.427155342449897557, -1688951.245373840210959315)
[07] MathExpr             (  721.783 ns,      -0.427155342449897557, -1688951.245373840210959315)
[08] muparser 2.2.4 (omp) (  758.253 ns,      -0.427155342449897557, -1688951.245373840210959315)
[09] muparser 2.2.4       (  769.149 ns,      -0.427155342449897557, -1688951.245373840210959315)
[10] TinyExpr             ( 1346.440 ns,      -0.427155342449897557, -1688951.245373840210959315)
[11] MTParser             ( 1355.477 ns,      -0.427155342449897557, -1688951.245373840210959315)
[12] Lepton               ( 1721.469 ns,      -0.427155342449897557, -1688951.245373840210959315)
[13] muparserx            ( 3007.245 ns,      -0.427155342449897557, -1688951.245373840210959315)

Expression 439 of 440: "((a+(a+(((e*(0.81*((cos((((sin(cos((((((((tan((((((sin((cos((tan(sin(tan(((tan(tan(((((sin((((((b*3.14)+pi)-pi)-a)+pi))/b)-a)-a)+e)))*a)+a))))+a))*3.98))+b)/pi)+3.03)+3.90)+2.97))/0.03)+1.83)-3.34)*b)+b)-1.39)+a)))*a)+1.54)-pi))/3.98)*pi)))+a)-b)))+a)"; Progress: #############
[01] ExprTk               (  457.896 ns,       1.428899180978623118, 18477825.075372278690338135)
[02] FParser 4.5          (  530.754 ns,       1.428899180978027594, 18477825.075372274965047836)
[03] METL                 (  546.004 ns,       1.428899180978047578, 18477825.075372274965047836)
[04] atmsp 1.0.4          (  650.973 ns,       1.428899180978047578, 18477825.075372274965047836)
[05] MathExpr             (  662.665 ns,       1.428899180978047578, 18477825.075372274965047836)
[06] muparser 2.2.4       (  667.349 ns,       1.428899180978047578, 18477825.075372274965047836)
[07] muparser 2.2.4 (omp) (  670.692 ns,       1.428899180978047578, 18477825.075372274965047836)
[08] TinyExpr             ( 1258.103 ns,       1.428899180978047578, 18477825.075372274965047836)
[09] MTParser             ( 1377.108 ns,       1.428899180978047578, 18477825.075372274965047836)
[10] Lepton               ( 1727.235 ns,       1.428899180978047578, 18477825.075372274965047836)
[11] muparserx            ( 2922.912 ns,       1.428899180978047578, 18477825.075372274965047836)
DNQ List
[01] muparserSSE          (  431.191 ns,       1.428969979286193848, 18477998.077869415283203125)
[02] ExprTkFloat          (  502.483 ns,       1.428736090660095215, 18477408.587932586669921875)

Expression 440 of 440: "(b-cos(sin(tan(cos(((sin(((((sin(((((3.70+(2.48+sin((b/(sin(((3.46*sin(sin(((cos((cos(sin(((tan(((((0.74*((sin((0.10-((cos(cos((tan(a)/a)))+2.68)-b)))*b)*b))+pi)-2.83)-b))+a)+pi)))*0.89))/pi)+b))))+3.72))*a)))))+e)+e)/pi))*1.03)*2.24)+b)/a))/pi)+1.53))))))"; Progress: #############
[01] ExprTk               (  552.882 ns,       1.204916613817216930, 3285153.514378606341779232)
[02] FParser 4.5          (  603.849 ns,       1.204916613817216930, 3285153.514378606341779232)
[03] ExprTkFloat          (  632.167 ns,       1.204916715621948242, 3285153.806209564208984375)
[04] muparserSSE          (  639.217 ns,       1.204916715621948242, 3285153.955221176147460938)
[05] METL                 (  657.940 ns,       1.204916613817216930, 3285153.514378606341779232)
[06] atmsp 1.0.4          (  678.803 ns,       1.204916613817216930, 3285153.514378606341779232)
[07] MathExpr             (  716.970 ns,       1.204916613817216930, 3285153.514378606341779232)
[08] muparser 2.2.4       (  800.842 ns,       1.204916613817216930, 3285153.514378606341779232)
[09] muparser 2.2.4 (omp) (  801.962 ns,       1.204916613817216930, 3285153.514378606341779232)
[10] MTParser             ( 1331.016 ns,       1.204916613817216930, 3285153.514378606341779232)
[11] TinyExpr             ( 1370.218 ns,       1.204916613817216930, 3285153.514378606341779232)
[12] Lepton               ( 1589.529 ns,       1.204916613817216930, 3285153.514378606341779232)
[13] muparserx            ( 2844.266 ns,       1.204916613817216930, 3285153.514378606341779232)
```

-----------

My thinking is perhaps there could be an issue with the Exprtk specific python to backend layer?...

**Comment by regislebrun** [comment]
The formula I use is HUGE: 10203269 chars! It is given in the attached (compressed) file
[formula.zip](https://github.com/openturns/openturns/files/3857585/formula.zip)

The input variables range from x0000 to x1999.

Do you confirm your findings regarding the speed of ExprTk vs MuParser on such huge expressions?

Cheers

**Comment by ArashPartow** [comment]
@regislebrun you are absolutely right and both points.

```
ss: ##
[01] muparser 2.2.4       (18103305.000 ns, 2349940647326324297360736256.000000000000000000, 23499406473263242423851548672.000000000000000000)
[02] ExprTk               (25403346.200 ns, 2349940647326324297360736256.000000000000000000, 23499406473263242423851548672.000000000000000000)

```

**Pull request closed without merging**
