### PR TITLE
CI: Store doc pages artifacts

### PR DESCRIPTION
**Pull request by jschueller**
simpler implementation of #1783

### CODE REVIEW

**Comment by josephmure** [comment]
The drawback of this implementation is that a single Python or C++ unit test timeout is enough to prevent the doc being stored, and these timeouts happen often. There will be cases where we will use the GitHub web interface to make a small change in the doc and won't be able to see the result because an unrelated test will have timed out.

**Comment by jschueller** [comment]
I've made several tests shorter rencently to adress these timeouts.

**Comment by josephmure** [comment]
Still, what is the issue with splitting the build and the test phase?

**Comment by jschueller** [comment]
It it breaking the build_locally script.

**Comment by josephmure** [comment]
Can you tell me how to fix it?

**Pull request merged**
