### PR TITLE
Move the _static dir

### PR DESCRIPTION
**Pull request by KieranDelamotte**
Fixing the issue with the search box.

### CODE REVIEW

**Review by jschueller — APPROVED** [review]
+1
could you mention the issue in the changelog, and in the commit body: "Closes #1616"

**Comment by jschueller** [comment]
I think it must be in the commit body instead of the title: "Closes #1616"

**Comment by KieranDelamotte** [comment]
Ok I change it again with

Move the _static directory

The _static directory is moved to solve the issue #1616 with the search box.


Is it good for you ?

**Comment by jschueller** [comment]
It must be explicitely "Closes #1616" so that the issue is closed automatically

**Review by josephmure — APPROVED** [review]
Good that you've fixed the search box error!

**Pull request merged**
