### PR TITLE
Fix matrix multiplication operators

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by sofianehaddad** [comment]
+1

**Comment by regislebrun** [comment]
It would be a good thing to be able to multiply real matrices with complex matrices.. Otherwise ok for this PR.

**Comment by jschueller** [comment]
@regislebrun, Matrix/ComplexMatrix product is now possible

**Comment by jschueller** [comment]
@regislebrun, I left aside the matrix/complexmatrix multiplication, see http://trac.openturns.org/ticket/802

**Pull request merged**
