### PR TITLE
Fixed a bug in GaussProductExperiment

### PR DESCRIPTION
**Pull request by regislebrun**
The constructor based only on marginal indices was wrong for dimension>1 as the dimension of the indices was not compatible with the dimension of the default distribution (=1).

### CODE REVIEW

**Comment by jschueller** [comment]
+1

**Comment by dbarbier** [comment]
+1

**Comment by jschueller** [comment]
@regislebrun this is weird, this broke otrobopt non-uniform results

**Comment by regislebrun** [comment]
@jschueller Ongoing compilation, more news this evening!

**Pull request merged**
