### PR TITLE
VisualTest: Deprecated CDF/Histogram/Cloud graphs

### PR DESCRIPTION
**Pull request by jschueller**
Rationale: These are not doing much except calling UserDefined services

### CODE REVIEW

**Comment by regislebrun** [comment]
+1

**Comment by mbaudin47** [comment]
Given the "destructive" effects, I would suggest to add a few comments in the ChangeLog, e.g.:

To update to OT 1.13, please replace:
ot.VisualTest.DrawEmpiricalCDF(sample)
with:
ot.UserDefined(sample).drawCDF()

To update to OT 1.13, please replace:
ot.VisualTest_DrawHistogram(sample)
with:
ot.HistogramFactory().build(sample).drawPDF()

This might be helpful for users.

**Comment by mbaudin47** [comment]
I cannot compile the doc, and this might be related to this commit:
```
[...]
sphinx.errors.SphinxWarning: /home/osboxes/GIT/openturns/build/python/src/sphinx_build/user_manual/_generated/openturns.VisualTest_DrawClouds.rst:document isn't included in any toctree

Warning, treated as error:
/home/osboxes/GIT/openturns/build/python/src/sphinx_build/user_manual/_generated/openturns.VisualTest_DrawClouds.rst:document isn't included in any toctree
make[2]: *** [python/src/CMakeFiles/sphinx_html.dir/build.make:542: python/src/CMakeFiles/sphinx_html] Error 2
make[1]: *** [CMakeFiles/Makefile2:26678: python/src/CMakeFiles/sphinx_html.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

**Comment by jschueller** [comment]
nah, just remove /build/python/src/sphinx_build and rebuild

**Comment by mbaudin47** [comment]
Thanks !

**Comment by mbaudin47** [comment]
What about the suggestion on the changes that must be applied to the code to update from 1.12 to 1.13. Would'nt it be appropriate to insert the text into the changelog ?

**Pull request merged**
