### PR TITLE
Improved GeneralizedLinearModelAlgorithm and KrigingAlgorithm

### PR DESCRIPTION
**Pull request by adutfoy**
The main improvement is to delegate to LAPACK the solution of the least-squares problem for the trend computation instead of doing it by hand using a QR decomposition (it is exactly what LAPACK do, but faster).

The other improvements are cosmetic: better agreement with coding rules, renaming of protected methods and attributes.

### CODE REVIEW

**Comment by regislebrun** [comment]
+1

**Comment by jschueller** [comment]
We agreed on using the copy operator for atomic types initialization:
http://openturns.github.io/developer_guide/coding_rules.html#assignment-and-initialization

**Comment by jschueller** [comment]
+1

**Comment by dbarbier** [comment]
I was interested in reviewing changes about QR decomposition but gave up since it is mixed with lots of cosmetic changes, it takes too much time to find meaningful changes.

**Comment by regislebrun** [comment]
@dbarbier The changes are in GeneralizedLinearModelAlgorithm.cxx lines 648-652. I merged too much commits during the rebase, sorry.

**Pull request merged**
