### PR TITLE
Improved Solver stability

### PR DESCRIPTION
**Pull request by regislebrun**
The Bisection, Brent and Secant solvers implemented the change of sign test in a way sensitive to underflow and overflow. Now it uses a test based on individual signs instead of a product. This fixes issue #1805.
The Beta::computeCharacteristicFunction() method has a long standing bug which is fixed by this PR. It fixes issue #1807.
With version 4.0.0, chaospy has changed its stochastic dependence management. The ChaospyDistribution class has been updated to take this change into account.

### CODE REVIEW

**Review by jschueller — APPROVED** [review]
test file seems missing though

**Comment by regislebrun** [comment]
@jschueller See t_Solver_hard.py

**Comment by mbaudin47** [comment]
The fix is good, but there are failing unit tests:
```
The following tests FAILED:
	505 - pyinstallcheck_Study_saveload (Failed)
	677 - pyinstallcheck_Brent_std (Failed)
	678 - pyinstallcheck_Bisection_std (Failed)
	679 - pyinstallcheck_Secant_std (Failed)
	680 - pyinstallcheck_Solver_hard (Failed)
	1018 - pyinstallcheck_DirectionalSampling_std (Failed)
	1022 - pyinstallcheck_AdaptiveDirectionalSampling_flood (Failed)
	1023 - pyinstallcheck_AdaptiveDirectionalSampling_hyperplane (Failed)
```
Some .expout files must be updated to fix this.

**Comment by regislebrun** [comment]
@jschueller I published ASAP to avoid having others starting to work on these issues. Where do I find the draft label?

**Comment by jschueller** [comment]
its on the right, under "Reviewers": "Still in progress? convert to draft"
also you can assign issues to yourself

**Comment by regislebrun** [comment]
Chez moi je ne vois pas de "Still in progress", cf capture jointe. Il faut régler quelque chose de particulier?
A++
Régis


    Le jeudi 25 mars 2021 à 19:13:29 UTC+1, Julien Schueller ***@***.***> a écrit :  
 
 


its on the right, under "Reviewers": "Still in progress? convert to draft"
also you can assign issues to yourself

**Comment by jschueller** [comment]
its marked Draft in the upper left corner, also it appears in grey color in the list of PRs

**Comment by regislebrun** [comment]
Ouppss! Sorry for the answer in French. This PR is marked as draft because I clicked on the link you sent to me. But I can't see any button allowing me to do it by myself on the github interface...

**Review by jschueller — APPROVED** [review]
+1
mingw gives a slightly different result and fails the assert

**Comment by regislebrun** [comment]
I had to change a little bit the tests to avoid spurious rounding depending on the use of 64bits floats or 80 bits floats.

**Review by sofianehaddad — APPROVED** [review]

**Pull request merged**
