### PR TITLE
Fix Collection objects Python comparison

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by sofianehaddad** [comment]
+1

**Comment by dbarbier** [comment]
+1, but why do we have to define `__eq__` in the first place?  This fix is too specific IMHO, the problem is broader.  BTW python operator '!=' is wrong, we must also define `__ne__` methods.

**Comment by jschueller** [comment]
@dbarbier I added a new macro to fix all these

**Comment by sofianehaddad** [comment]
+1

**Pull request merged**
