### PR TITLE
Unity builds

### PR DESCRIPTION
**Pull request by jschueller**
Use cotire cmake module: https://github.com/sakra/cotire

This allows to speed-up builds of libOT by using fewer compilation units.
This option speeds up one time builds but incremental builds will be slower.
This can be used for continuous integration or producing binaries.

Using USE_COTIRE=ON disables the sphinx doc and the bison/flex parser as it does not play well with custom rules.

### CODE REVIEW

**Comment by dbarbier** [comment]
Description?

**Comment by jschueller** [comment]
@dbarbier see 3987ff0:

This allows to speed-up builds of libOT by using fewer compilation
units.
This option speeds up one time builds but incremental builds will be
slower.
This can be used for continuous integration or producing binaries.

**Comment by dbarbier** [comment]
+1

**Comment by regislebrun** [comment]
+1

**Pull request merged**
