### PR TITLE
Rename Field properties

### PR DESCRIPTION
**Pull request by jschueller**
see http://trac.openturns.org/ticket/928

### CODE REVIEW

**Comment by dbarbier** [comment]
Slightly related, what do you think of renaming `CovarianceModel::partialGradient` method to `spatialGradient`?

**Comment by jschueller** [comment]
I thought we wanted to get rid of the 'spatial' term :question:

**Comment by regislebrun** [comment]
@dbarbier the name comes from the fact that it returns dC(s,t)/ds and not [dC(s,t)/ds, dC(s,t)/dt], so only half of the gradient is returned (which is enough due to the symmetry of C wrt s and t). Do you want to contrast this method from the parameter gradient with the new name?

**Comment by dbarbier** [comment]
@regislebrun Ok, if there is an explanation for partialGradient, this is fine by me.

**Comment by jschueller** [comment]
If it's ok for you I like to merge that before #584 & #590.

**Comment by dbarbier** [comment]
Okay for me; I edited my PR, these branches are only Requests For Comments (RFC) for now.

**Comment by jschueller** [comment]
@regislebrun is this ok for you ?

**Comment by regislebrun** [comment]
+1

**Pull request merged**
