### PR TITLE
New orthogonal basis

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
@regislebrun, I wrote a simpler Log2

**Comment by regislebrun** [comment]
No! The previous one was delightful! My previous comment was a compliment!

**Comment by jschueller** [comment]
@regislebrun, ok, I put it back, with comments

**Comment by regislebrun** [comment]
I have some doubts on the implementation of the CanonicalTensor class. It will have to store a collection of DesignProxy that will be shared among the different rank one tensors.

**Comment by regislebrun** [comment]
+1

**Pull request merged**
