### PR TITLE
added XMLH5StorageManager

### PR DESCRIPTION
**Pull request by YomGarcia**

### CODE REVIEW

**Comment by GuiGag** [comment]
I present a new storage solution for openturns studies. The XML file is still present and used as a header file. Heavy data would be stored into a binary HDF5 file, format which present a few advantages compared to pure ASCII storage, especially for large data.

Below follows a comparison of file size and writing time as a function of the 2xN sample size containing floats
For sample sizes > 30 HDF5 present an advantage wrt file size and for sizes >100 it is faster writing HDF5 datasets instead of appending the XML study file. Storing heavy data this way allows for a factor ~10 gain in file size

FileSize_WritingTime_Comp

Openturns default behaviour is not modified. The new storage manager is used through Study::setStorageManager() (see tests)
Note that this subject is still work in progress and (of course) open to discussion

**Comment by regislebrun** [comment]
Hi,
Many thanks for this contribution, which looks very promising. I get an error when I try to compile your branch:
```
[  2%] Building CXX object lib/src/CMakeFiles/OT.dir/Base/Common/XMLH5StorageManager.cxx.o
In file included from /usr/include/c++/8.4.0/cassert:44,
                 from /home/regis/openturns-guigag/lib/src/Base/Common/openturns/AtomicInt.hxx:24,
                 from /home/regis/openturns-guigag/lib/src/Base/Common/openturns/Log.hxx:27,
                 from /home/regis/openturns-guigag/lib/src/Base/Common/openturns/ResourceMap.hxx:27,
                 from /home/regis/openturns-guigag/lib/src/Base/Common/openturns/XMLStorageManager.hxx:31,
                 from /home/regis/openturns-guigag/lib/src/Base/Common/openturns/XMLH5StorageManager.hxx:25,
                 from /home/regis/openturns-guigag/lib/src/Base/Common/XMLH5StorageManager.cxx:23:
/home/regis/openturns-guigag/lib/src/Base/Common/XMLH5StorageManager.cxx: Dans la fonction membre « virtual void OT::XMLH5StorageManager::readIndexedValue(OT::Pointer<OT::StorageManager::InternalObject>&, OT::UnsignedInteger, OT::Scalar&) »
/home/regis/openturns-guigag/lib/src/Base/Common/XMLH5StorageManager.cxx:149:3: error: « static_cast » invalide depuis le type « OT::XMLH5StorageManagerState » vers le type « bool »
   assert(state);
   ^~~~~~
```
Any clue to solve it?

**Comment by GuiGag** [comment]
I can't seem to reproduce it. I tried turning on some cmake flags, namely: 
`-Wall -Wextra -Wno-unused-parameter -D_GLIBCXX_ASSERTIONS`
maybe it is coming from there. Which ones do you have currently on?

**Comment by regislebrun** [comment]
@GuiGag I use the following flags:
`-Wall -Wextra -O3 -mfpmath=sse -mtune=native -march=native -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -maes -msse4 -mmmx`
I use this compiler:
```
Utilisation des specs internes.
COLLECT_GCC=/usr/bin/g++-8.4.0
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-mageia-linux-gnu/8.4.0/lto-wrapper
Cible : x86_64-mageia-linux-gnu
Configuré avec: ../configure --prefix=/usr --libexecdir=/usr/lib --with-slibdir=/lib64 --with-pkgversion='Mageia 8.4.0-1.mga7' --with-bugurl=https://bugs.mageia.org/ --mandir=/usr/share/man --infodir=/usr/share/info --enable-checking=release --enable-languages=c,c++,ada,fortran,objc,obj-c++ --enable-linker-build-id --build=x86_64-mageia-linux-gnu --host=x86_64-mageia-linux-gnu --with-cpu=generic --with-system-zlib --enable-threads=posix --with-linker-hash-style=gnu --enable-shared --enable-long-long --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --enable-ssp --disable-libssp --disable-libffi --disable-werror --with-isl --with-python-dir=/lib/python2.7/site-packages --enable-lto
Modèle de thread: posix
gcc version 8.4.0 (Mageia 8.4.0-1.mga7) 
```
Not the most recent one, but reasonably modern.
I was wondering if you also made a benchmark against the CSV&text import/export for samples? They should be slower than your HDF5 proposal but not by such a huge margin.
Many thanks for this contribution!

**Review by sofianehaddad — APPROVED** [review]

**Pull request merged**
