### PR TITLE
Fix RandomMixture::getSample

### PR DESCRIPTION
**Pull request by dbarbier**
This commit fixes trac#888.

### CODE REVIEW

**Comment by dbarbier** [comment]
Improved description in commit message, no code change. New message is:

    Fix RandomMixture::getSample
    
    This commit fixes trac#888.
    
    Here is a simple test case:
    
      import openturns as ot
      mixture = ot.RandomMixture([ot.Bernoulli(), ot.Normal(10, 0.1)])
      mixture.getSample(10)
    
    Output before this commit:
    
      class=Sample name=Unnamed implementation=class=SampleImplementation name=Unnamed size=10 dimension=1
      data=[[0],[2],[1],[0],[2],[19.9995],[20.2248],[20.0323],[19.7971],[19.7405]]
    
    Output after this commit:
    
      class=Sample name=Unnamed implementation=class=SampleImplementation name=Unnamed size=10 dimension=1
      data=[[10.035],[9.9645],[11.1437],[11.0811],[11.0793],[9.95295],[10.0261],[9.77099],[10.8717],[10.8688]]
    
    This is because elements in the sample matrix were inserted in wrong order:
    
       Bernoulli()  Normal(10,0.1)        Bernoulli()  Normal(10,0.1)
       [   0           0       ]            [  0          10.035   ]
       [   1           1       ]            [  0           9.9645  ]
       [   1           0       ]            [  1          10.1437  ]
       [   0           0       ]            [  1          10.0811  ]
       [   1           1       ] instead of [  1          10.0793  ]
       [  10.035       9.9645  ]            [  0           9.95295 ]
       [  10.1437     10.0811  ]            [  0          10.0261  ]
       [  10.0793      9.95295 ]            [  0           9.77099 ]
       [  10.0261      9.77099 ]            [  1           9.87171 ]
       [   9.87171     9.86882 ]            [  1           9.86882 ]

**Comment by dbarbier** [comment]
Err, just found that I accidentally dropped a `transpose()`, sorry.  I will also swap left and right matrices to avoid this transpose.

**Comment by dbarbier** [comment]
@jschueller Out of curiosity, are you waiting for some input to merge this PR?

**Comment by jschueller** [comment]
Yes, @regislebrun.

**Comment by dbarbier** [comment]
But there is clearly a bug which is fixed by this commit.

**Comment by jschueller** [comment]
Ok, if this blocks you.

**Comment by dbarbier** [comment]
Thanks

**Pull request merged**
