### PR TITLE
Lagrange multipliers

### PR DESCRIPTION
**Pull request by regislebrun**
Added the computation of Lagrange multipliers to optimization solvers.
    
    Only AbdoRackwitz and SQP include a computation of the Lagrange multipliers as an element of the resolution. For Cobyla, TNC and the NLopt algorithms, the multipliers are computed using the generic implementation.

### CODE REVIEW

**Comment by jschueller** [comment]
ok, but t_Cobyla_std test fails for now on i686-linux

**Comment by regislebrun** [comment]
I found additional troubles, eg the TNC algorithm computes a convergence history but does not store it, and the optimal value is stored as a 2D NumericalPoint in Cobyla. I have fixed almost everything, and hopefully it will resolve the pb with cobyla on i686.

**Comment by jschueller** [comment]
It seems some kriging tests fail for 32 bits:
http://autobuilder.openturns.org/openturns/pull/186/squeeze-i386-ot-linux/

**Comment by adutfoy** [comment]
+1

**Comment by dbarbier** [comment]
Hello, any news on this one?

**Comment by regislebrun** [comment]
@dbarbier I have an emergency (an internal project that ends... tomorrow!). The code looks all right on my local copy, but I still have to check the documentation.

**Comment by jschueller** [comment]
+1

**Comment by jschueller** [comment]
@sofianehaddad, @dbarbier, this one finally passes the tests, what do you say ?

**Comment by jschueller** [comment]
@regislebrun there's a small conflict tough, maybe because of resourcemap

**Comment by dbarbier** [comment]
+1

**Comment by regislebrun** [comment]
YES!

**Pull request merged**
