### PR TITLE
Fix RandomMixture::isContinuous

### PR DESCRIPTION
**Pull request by jschueller**
(doesn't fix last ticket)

### CODE REVIEW

**Comment by dbarbier** [comment]
Description is useless, I am unable to understand the rationale of this PR.

**Comment by jschueller** [comment]
I thought RandomMixture was only continuous if all variables are continuous, but I went too quick.

**Comment by sofianehaddad** [comment]
@jschueller exact but finally the PR highlights other problems (see http://trac.openturns.org/ticket/887)

**Comment by jschueller** [comment]
Yes, also, it seems it doesn't play well for discrete+continuous.

**Pull request closed without merging**
