### PR TITLE
Stoch proc doc

### PR DESCRIPTION
**Pull request by adutfoy**
Added the documentation for the Dickey Fuller test and enforced the use of the \Tr LaTeX command for transposition.

### CODE REVIEW

**Comment by jschueller** [comment]
+1

**Comment by sofianehaddad** [comment]
+1, maybe you can squash d713e49 and 4380d3e

**Comment by jschueller** [comment]
There's a problem with swig:
http://autobuilder.openturns.org/openturns/pull/91/squeeze-x86_64-ot-linux/distcheck-launcher.log

Are these titles ok ?
```
**1.** We assume the model :eq:`Model1`:
```

**Comment by jschueller** [comment]
There's a problem with swig:
http://autobuilder.openturns.org/openturns/pull/91/squeeze-x86_64-ot-linux/distcheck-launcher.log

**Pull request merged**
