### PR TITLE
Speed-up conversion from 2-d Python sequence into Sample

### PR DESCRIPTION
**Pull request by dbarbier**

### CODE REVIEW

**Comment by regislebrun** [comment]
+1

**Comment by jschueller** [comment]
Did you test this with python3 ?

**Comment by dbarbier** [comment]
No, this is mostly copy/paste thus I did not expect any breakage.  And I thought that this was tested by CI, we should definitely test with Python3.

**Comment by jschueller** [comment]
Python3 is tested on the autobuilder, sorry.

**Pull request merged**
