### PR TITLE
Fix RPATH handling on Mac OSX and remove SYSTEM_INSTALL

### PR DESCRIPTION
**Pull request by dbarbier**
The canonical way to prevent rpath from being used is to set
CMAKE_SKIP_RPATH or CMAKE_SKIP_INSTALL_RPATH options.

### CODE REVIEW

**Comment by dbarbier** [comment]
It this works fine on OSX, pull request #41 is no more needed.

**Comment by sofianehaddad** [comment]
+1, the patch fixes the issue. 
DYLD_LIBRARY_PATH is no more required for installcheck.
Also, Python bidding works fine without specification of the DYLD_LIBRARY_PATH variable
#41 has been closed.

**Comment by dbarbier** [comment]
Great news, thanks for testing.

**Comment by jschueller** [comment]
I think packages will need to be patched to disable rpaths.

**Comment by jschueller** [comment]
+1

**Pull request merged**
