### PR TITLE
Use std::abs(double) instead of abs(int)

### PR DESCRIPTION
**Pull request by jschueller**
abs comes from stdlib.h on operates on int

### CODE REVIEW

**Comment by jschueller** [comment]
Maybe we could agree to use std::abs everywhere, which is more c++-ish (224 occurences) for consistency instead of fabs (215 occurences), which comes from math.h (c lib).

**Comment by regislebrun** [comment]
Agree. Who is volunteer for the task?

**Comment by jschueller** [comment]
I can do it, it's just a sed command, but I refrained from doing so because of all the active branches, maybe I could do it after the dust settles.

**Comment by dbarbier** [comment]
+1, and there is another occurence in `GeneralizedLinearModelAlgorithm.cxx`.

**Comment by jschueller** [comment]
@dbarbier, yes @sofianehaddad took care of it

**Comment by dbarbier** [comment]
@jschueller There is no PR yet, it is better to fix it in this PR.

**Comment by jschueller** [comment]
@dbarbier, @sofianehaddad, ok, reverted

**Pull request merged**
