### PR TITLE
NumericalMathFunction API consistency

### PR DESCRIPTION
**Pull request by jschueller**
For consistency with Distribution, CovarianceModel.

### CODE REVIEW

**Comment by dbarbier** [comment]
+1, please document API changes in ChangeLog too.

**Comment by sofianehaddad** [comment]
+1

**Comment by jschueller** [comment]
@dbarbier, ok

**Comment by jschueller** [comment]
@regislebrun, what do you say about this one ?

**Comment by regislebrun** [comment]
We added the flag on the use of the default implementation for gradients because in many occasions we got questions regarding strange results in QuadraticCumul or FORM/SORM during trainings, the reason of the problem being the bad choice of step in finite difference. We (ie Anne and myself) think that it should be kept, or something equivalent should be implemented.
Otherwise it is a big +1

**Comment by jschueller** [comment]
@regislebrun, ok I think you're just interested in the console warning, maybe these methods should be kept 'protected' to the class ?

**Comment by regislebrun** [comment]
Yes indeed.

**Comment by jschueller** [comment]
@regislebrun: update, these are ignored at the python level, also removed the get/setInitial(grad|hess)Implementation that are useless and also incorrectly implemented

**Comment by regislebrun** [comment]
+1

**Pull request merged**
