### PR TITLE
Always return Interface instead of Pointer<Implementation>

### PR DESCRIPTION
**Pull request by dbarbier**
DistributionImplementation::getCopula -> Distribution
  DistributionImplementation::getMarginal -> Distribution
  DistributionImplementation::getStandardRepresentative -> Distribution
  DistributionImplementation::getStandardDistribution -> Distribution
  DistributionFactoryImplementation::build -> Distribution
  ProcessImplementation::getMarginal -> Process
  RandomVector::getAntecedent -> RandomVector
  RandomVector::getMarginal -> RandomVector

### CODE REVIEW

**Comment by dbarbier** [comment]
My aim is eventually to remove SWIG_TypeQuery from TypedInterfaceObject.i to make bindings faster, but all methods which return a Pointer without a good reason must be fixed first.

**Comment by jschueller** [comment]
I hope this works : )

**Comment by regislebrun** [comment]
+1

**Comment by dbarbier** [comment]
Branch updated, everything should now be in shape.  This may have an import on modules, I hope not.

**Comment by jschueller** [comment]
Only otmixmod seems impacted, could you update it ?

**Comment by dbarbier** [comment]
PR sent for otmixmod.

**Pull request merged**
