### PR TITLE
Updated the theoretical documentation of BIC to match the implementation

### LINKED ISSUE #989: dummy issue #989
please ignore

### PR DESCRIPTION
**Pull request by mbaudin47**
Fixes http://trac.openturns.org/ticket/989

### CODE REVIEW

**Comment by jschueller** [comment]
You forgot to update the Changelog

**Comment by mbaudin47** [comment]
Hope I did well :)

**Comment by mbaudin47** [comment]
How can I solve the "continuous-integration/appveyor/pr — AppVeyor build failed " issue ?
```
Build started
git clone -q https://github.com/openturns/openturns.git C:\projects\openturns
git fetch -q origin +refs/pull/1021/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
appveyor-retry appveyor DownloadFile https://downloads.sourceforge.net/openblas/v0.2.15/OpenBLAS-v0.2.15-Win32.zip
Error downloading remote file: One or more errors occurred.
Inner Exception: Remote server returned 502: Bad Gateway
Command "appveyor DownloadFile https://downloads.sourceforge.net/openblas/v0.2.15/OpenBLAS-v0.2.15-Win32.zip" failed with exit code 2. Retrying 2 of 3
Error downloading remote file: One or more errors occurred.
Inner Exception: Remote server returned 502: Bad Gateway
Command "appveyor DownloadFile https://downloads.sourceforge.net/openblas/v0.2.15/OpenBLAS-v0.2.15-Win32.zip" failed with exit code 2. Retrying 3 of 3
Error downloading remote file: One or more errors occurred.
Inner Exception: Remote server returned 502: Bad Gateway
Sorry, we tried running command for 3 times and all attempts were unsuccessful!
Command exited with code 2
```

**Comment by mbaudin47** [comment]
Is this PR ok ?

**Comment by regislebrun** [comment]
+1

**Pull request merged**
