### PR TITLE
Fix http://trac.openturns.org/ticket/937

### PR DESCRIPTION
**Pull request by sofianehaddad**
In PenalizedLeastSquaresAlgorithm, no need to normalize with weights as
it is already used for solving the linear system.

### CODE REVIEW

**Comment by jschueller** [comment]
I dont get the same results on the t_PenalizedLeastSquaresAlgorithm_std.py with your patch:
```
outputSample = model(inputSample)
coefs = algo.getCoefficients()
mm=LinearCombinationFunction(coll, coefs)
N=size*size
quadraticResidual = 0.0
for i in range(N):
    quadraticResidual += (outputSample[i, 0] - mm(inputSample[i])[0])**2.0
residual = m.sqrt(quadraticResidual) / N
print("Residual=%g" % algo.getResidual(), residual)
```
Residual=0.0590532 0.022443370303890348

**Comment by sofianehaddad** [comment]
@jschueller only the `uniform & no penalization part`  is impacted by this PR

The returned residual in that case correspond to the following uc:

```
outputSample = model(inputSample)
coefs = algo.getCoefficients()
mm=LinearCombinationFunction(coll, coefs)
N=inputSample.getSize()
quadraticResidual = 0.0
for i in range(N):
    quadraticResidual += (outputSample[i, 0] * m.sqrt(weight[i]) - m.sqrt(weight[i]) * mm(inputSample[i])[0])**2.0
residual = m.sqrt(quadraticResidual) / N
print("Residual=%g" % algo.getResidual(), residual)
```

**Comment by jschueller** [comment]
Ok, my bad I used the wrong weight variable while simplifying the script.

**Comment by regislebrun** [comment]
+1

**Comment by jschueller** [comment]
Please update the ChangeLog to mention the bug.
Also I'd prefer the commit message to mention the actual change rather than the ticket url, imho the ticket url can go to the commit message body.

**Comment by jschueller** [comment]
Cool, thanks

**Pull request merged**
