### PR TITLE
Fix Sample html conversion

### PR DESCRIPTION
**Pull request by jschueller**
See http://trac.openturns.org/ticket/943

Introduced in https://github.com/openturns/openturns/pull/633/commits/fbafb39fd43967cf2d38d44b548f4d981ace030e

### CODE REVIEW

**Comment by regislebrun** [comment]
+1

**Comment by jschueller** [comment]
@dbarbier @regislebrun this adds build dependency to swig>=2.0.9

**Comment by dbarbier** [comment]
@jschueller No problem for me with this dependency

**Comment by regislebrun** [comment]
@jschueller Ok too if it doesn't cause trouble with the different OT packages

**Pull request merged**
