### PR TITLE
Add Point, Matrix unary minus

### LINKED ISSUE #1153: Unitary minus for points and matrices
```
import openturns as ot
A = ot.Matrix(3,3)
B = -A
```
produces
```
TypeError: bad operand type for unary -: 'Matrix'
```

### PR DESCRIPTION
**Pull request by jschueller**
Closes #1153

### CODE REVIEW

**Comment by mbaudin47** [comment]
Thanks ! 
Note that the AppVeyor bug is a "Build execution time has reached the maximum allowed time for your plan (60 minutes).".

**Comment by regislebrun** [comment]
+1

**Comment by jschueller** [comment]
What do you mean any scalar ? element-wise minus/add ?

**Comment by sofianehaddad** [comment]
Yes, element-wise addition/substraction
We should implement **all** or **no one**! We can not provide "partial" operations like unary minus only...

**Comment by jschueller** [comment]
I do not agree : unary minus is an extension of scalar(-1)*vector, you'd want to add vector+-scalar, this is another subject, and we should consider the implications of this, I think there was a trac ticket about some possible downsides.

**Comment by sofianehaddad** [comment]
I missed the fact that Product is already implemented. Thus ok for this PR
Concerning +/- operations (http://trac.openturns.org/ticket/858) we will see later

**Pull request merged**
