### PR TITLE
Use sphinx git

### PR DESCRIPTION
**Pull request by jschueller**
Allows to keep an eye on sphinx development, requires to use numpydoc git too.

### CODE REVIEW

**Comment by regislebrun** [comment]
+1

**Comment by dbarbier** [comment]
+1

**Comment by jschueller** [comment]
Progressing on this, found an issue in Dirac, also maybe a bug in numpydoc git atm:
https://github.com/numpy/numpydoc/pull/93

**Comment by jschueller** [comment]
numpy/numpydoc#93 merged, new issue https://github.com/sphinx-doc/sphinx/issues/3874

**Comment by jschueller** [comment]
sphinx-doc/sphinx#3874 has been fixed, now need nbsphinx/pull/112

**Pull request merged**
