### PR TITLE
Speed-up QuadraticEvaluation and LinearGradient

### PR DESCRIPTION
**Pull request by dbarbier**

### CODE REVIEW

**Comment by dbarbier** [comment]
Good point, fixed now, thanks

**Comment by regislebrun** [comment]
+1

**Comment by dbarbier** [comment]
With commit bcee68

N | 50 | 100 | 200 | 400
--|--|--|--|--
nr. evaluation/s (master) | 1270 | 230 | 31.1 | 4.0
nr. evaluation/s (PR789) | 2803 | 758 | 314 | 82.3
nr. evaluation/s (bcee68) | 58380 | 26421 | 7137 | 1176
 | | | |
nr. gradient/s (master) | 601 | 76 | 7.5 | 0.68
nr. gradient/s (PR789) | 2536 | 844 | 377 | 84.1
nr. gradient/s (bcee68) | 2600 | 828 | 338 | 78.1

**Comment by regislebrun** [comment]
+1

**Pull request merged**
