### PR TITLE
Minor bugfix in documentation

### PR DESCRIPTION
**Pull request by sofianehaddad**
Fix http://trac.openturns.org/ticket/962

### CODE REVIEW

**Comment by jschueller** [comment]
needs a rebase

**Comment by jschueller** [comment]
Did you setup your git account correctly ?

**Comment by jschueller** [comment]
Your icon doesnt appear with your commit, perhaps you messed with the git user name or email ?

**Comment by sofianehaddad** [comment]
Should be fixed now :-)

**Pull request merged**
