### PR TITLE
Stationary covariance model factory doc

### PR DESCRIPTION
**Pull request by adutfoy**

### CODE REVIEW

**Comment by jschueller** [comment]
Could you squash these commit together ? see my comments for #63.

**Comment by jschueller** [comment]
This one has conflicts now, I guess because of #50.

**Comment by dbarbier** [comment]
+1

**Comment by sofianehaddad** [comment]
+1

**Comment by jschueller** [comment]
This PR has conflicts now, could you rebase so as to merge it ?

**Pull request merged**
