### PR TITLE
Spectral model doc

### PR DESCRIPTION
**Pull request by adutfoy**
It contains the documentation of the UserDefinedSpectralModel and SpectralModelFactory classes.

### CODE REVIEW

**Comment by sofianehaddad** [comment]
+1

**Comment by jschueller** [comment]
Could you squash these commit together ? see my comments for #63.

**Comment by adutfoy** [comment]
I squashed only two of the four commits as two are dedicated to the UserDefinedSpectralModel class and the others are for two different classes. Please tell me what you have in mind to suggest a unique commit.

**Comment by sofianehaddad** [comment]
+1

**Comment by jschueller** [comment]
It has conflicts now, because of #50 ?

**Comment by dbarbier** [comment]
+1, commits look good to me.

**Pull request merged**
