### PR TITLE
Use imgmath if available

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
Sphinx git version used by travis emits a warning treated as error as pngmath is deprecated.

**Comment by jschueller** [comment]
TODO: backport it into 1.7 branch to benefit from travis

**Comment by dbarbier** [comment]
+1, but please improve commit messages, I spent some time to understand reasons behind this PR.  To interested readers: this is to fix travis builds.

**Comment by jschueller** [comment]
@dbarbier ok done

**Comment by dbarbier** [comment]
@jschueller Thanks, much better for reviewers.

**Pull request merged**
