### PR TITLE
Clarified help page for the LogNormal and LogNormalMuSigma classes.

### LINKED ISSUE #1031: The doc for LogNormal and LogNormalMuSigma is confusing
The text inside: 
http://openturns.github.io/openturns/master/user_manual/_generated/openturns.LogNormal.html
and 
http://openturns.github.io/openturns/master/user_manual/_generated/openturns.LogNormalMuSigma.html
is not clear enough about the meaning of the parameters.

Within the LogNormal page, the text: 

muLogfloat : location parameter \mu_\ell.

should be replaced with:

muLogfloat : location parameter \mu_\ell, the expectation of log(X)

Within LogNormalMuSigma, the text 

mufloat: Mean.

should be replaced with:

mufloat: The mean of X.

After the text "The native parameters are defined as follows:" and the equation, we should insert: 

where $\mu_\ell$ (resp. $\sigma_l=\ell$) is the mean of log(X) (resp. the standard deviation of log(X)).

### PR DESCRIPTION
**Pull request by mbaudin47**
Fixes #1031.
The goal of the commit is to clarify the meaning of the mean and sigma parameters, be it for X or log(X).

### CODE REVIEW

**Comment by jschueller** [comment]
Same comment as in PR1022, and you can update the changelog

**Comment by jschueller** [comment]
Use rebase instead of merge to get rid of the merge commit.

**Comment by jschueller** [comment]
you're trying to erase my changes here ? :]

**Comment by mbaudin47** [comment]
Oups: I was able to get rid of the merge. But I guess I got rid of all the commits in my master.

**Comment by mbaudin47** [comment]
I didn't mean to erase your changes: it was a mistake on my side. The correct PR is #1042. This is why I leave this one closed.

**Pull request closed without merging**
