### PR TITLE
Michael new examples

### PR DESCRIPTION
**Pull request by josephmure**
This PR is the same as #1487 but with all "apply suggestion" commits squashed.
Let me quote @mbaudin47's original message:

 - KernelSmoothing: added an example for sensitivity to bandwidth
 - Metamodel: adding a new example for model selection
 - Polynomial chaos: explained the transformation
 - Polynomial chaos: adding an example to shows the sensitivity to the degree of the polynomial

### CODE REVIEW

**Comment by josephmure** [comment]
@KieranDelamotte can you please try to convert these notebooks to the new RST format?

**Comment by mbaudin47** [comment]
Well done: thanks!

**Comment by mbaudin47** [comment]
It seems that the circleci/linux build fails, with an unrelated error:
```
 from /home/devel/project/build/python/src/sphinx_build/theory/meta_modeling/enumeration_strategy.rst:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 472, in run_code
    exec(code, ns)
  File "<string>", line 65, in <module>
  File "/usr/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 63, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/matplotlib/axis.py", line 1793, in _set_ticklabels
    return self.set_ticklabels(labels, minor=minor, **kwargs)
  File "/usr/lib/python3.8/site-packages/matplotlib/axis.py", line 1714, in set_ticklabels
    raise ValueError(
ValueError: The number of FixedLocator locations (6), usually from a call to set_ticks, 
does not match the number of ticklabels (5).
```

**Comment by jschueller** [comment]
nevermind, that's an old matplotlib error, fixed some time ago
anyway I'm closing it now that typos are fixed since it's not going to be merged as is and depends on if @KieranDelamotte has the bandwith to pick these notebooks

**Pull request closed without merging**
