### PR TITLE
Improved Distribution::computeQuantile()

### PR DESCRIPTION
**Pull request by regislebrun**
Now, the quantile function is continuous. It fixes ticket #915.

### CODE REVIEW

**Comment by regislebrun** [comment]
@jschueller Maybe the underlying code was not so wrong ;-)

**Comment by jschueller** [comment]
We need some test

**Comment by regislebrun** [comment]
added tests. If the output is empty, it is ok (at least for all the univariate distributions with a factory).

**Comment by sofianehaddad** [comment]
Thanks, interesting test :-)

**Pull request merged**
