### PR TITLE
Better default NearestNeighbourAlgorithm

### PR DESCRIPTION
**Pull request by dbarbier**
Prefer RegularGridNearestNeighbour on a RegularGrid, it provides faster
instantiation and queries.

Add missing methods in RegularGridNearestNeighbour.

### CODE REVIEW

**Comment by regislebrun** [comment]
+1

**Comment by dbarbier** [comment]
Commits will cause trouble with #662, I need to rewrite them.

**Comment by dbarbier** [comment]
Okay, done, it was easier than expected.  I had to drop Field::[gs]etValueAtNearestPosition.

**Comment by regislebrun** [comment]
+1

**Pull request merged**
