### PR TITLE
Release 1.16

### PR DESCRIPTION
**Pull request by jschueller**
- some doc fixes
- a fix for coupling_tools.execute command parsing (https://openturns.discourse.group/t/error-lors-de-lutilisation-du-module-coupling-tools/58)
- rename some coupling_tools.execute arguments to match what's found in subprocess (cwd, check, shell, executable)
- a fix for SWIG when passing None arguments

### CODE REVIEW

**Comment by jschueller** [comment]
@regislebrun @sofianehaddad alles gut ?

**Review by regislebrun — APPROVED** [review]
There must be some bugs left, but they are for the next release!

**Comment by jschueller** [comment]
Yes, you dont want to be out of job by closing all the bugs

**Review by sofianehaddad — COMMENTED** [review]
sorry I missed this.
of course, it is ok

**Pull request merged**
