### PR TITLE
Improved ParametericFunction

### PR DESCRIPTION
**Pull request by regislebrun**
Now parameterGradient() is based on the underlying function gradient() instead of finite differences.

### CODE REVIEW

**Comment by jschueller** [comment]
oh, and pyinstallcheck_docstring_bayesian seems to fail now

**Comment by regislebrun** [comment]
Done (after 1h of torture with my physiotherapist...). Sorry for the duplicated work...

**Comment by mbaudin47** [comment]
Thank you very much ! After all, torture seems efficient...

**Comment by jschueller** [comment]
Needs a rebase after #1091

**Pull request merged**
