### PR TITLE
Set a global timeout on all tests

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by dbarbier** [comment]
-1, separate lines are much more readable

**Comment by jschueller** [comment]
@dbarbier, I want to avoid make tests & ctest for a quicker build result if make fails.

**Comment by dbarbier** [comment]
Ok, for reasons I do not understand, travis build does not abort when a command fails :(
Thus +1 from me, sorry for the confusion.

**Comment by regislebrun** [comment]
+1

**Pull request merged**
