### PR TITLE
Move header files into an openturns/ subdirectory

### PR DESCRIPTION
**Pull request by dbarbier**
Just like C++ namespaces prevent symbol name collisions, it is a good practice to use a prefix for header files.  Either a subdirectory (see boost for instance) or by using some prefix (see vtk for instance).

This pull request moves header files into an openturns/ subdirectory at each level.  Users will have to modify all their C++ files to replace
```
  #include <FooBar.hxx>
```
by
```
  #include <openturns/FooBar.hxx>
```

As header files were already installed under include/openturns/, this change is not as disruptive as it looks like, because one only has to modify -I compiler flags.  Of course, lazy developers may not change their habits, but we should promote the new #include usage.

Please consider this issue with caution, these changes are highly invasive.

### CODE REVIEW

**Comment by sofianehaddad** [comment]
+1

**Comment by jschueller** [comment]
+1
This will break modules c.i. on the autobuilder until 1.8 is released, but I guess this is acceptable given current module activity.
I did the same thing for module template : https://github.com/openturns/ottemplate/pull/10
Next step is to make modules use the new #include convention for OT headers, to be merged for the 1.8 release.

**Comment by regislebrun** [comment]
+1

**Comment by jschueller** [comment]
OPENTURNS_INCLUDE_DIRS is still [prefix]/include/openturns, is this expected ?
```set ( OPENTURNS_INCLUDE_DIRS "${PACKAGE_PREFIX_DIR}/include/openturns;/usr/include;/usr/lib64/cmake/hmat/../../../include/hmat;/usr/include/libxml2" )
```

**Comment by jschueller** [comment]
Actually few headers are installed in the subdir: (https://s3.amazonaws.com/archive.travis-ci.org/jobs/108567084/log.txt)
```
-- Installing: /home/travis/.local/include/CompositeProcess.hxx
-- Installing: /home/travis/.local/include/FunctionalBasisProcess.hxx
-- Installing: /home/travis/.local/include/ARMAFactoryImplementation.hxx
-- Installing: /home/travis/.local/include/ARMAFactory.hxx
-- Installing: /home/travis/.local/include/WhittleFactory.hxx
-- Installing: /home/travis/.local/include/WhittleFactoryState.hxx
-- Installing: /home/travis/.local/include/ARMALikelihoodFactory.hxx
-- Installing: /home/travis/.local/include/ConditionedNormalProcess.hxx
-- Installing: /home/travis/.local/include/openturns
-- Installing: /home/travis/.local/include/openturns/OTconfig.hxx
-- Installing: /home/travis/.local/include/openturns/OTdebug.h
-- Installing: /home/travis/.local/include/openturns/OTmemory.hxx
-- Installing: /home/travis/.local/include/openturns/OTprivate.hxx
-- Installing: /home/travis/.local/include/openturns/OTtestcode.hxx
-- Installing: /home/travis/.local/include/openturns/OTthread.hxx
-- Installing: /home/travis/.local/include/openturns/OTtypes.hxx
-- Installing: /home/travis/.local/include/openturns/OTwindows.h
-- Installing: /home/travis/.local/include/openturns/OTconfig.h
-- Installing: /home/travis/.local/include/openturns/installed-OTconfig.h
-- Installing: /home/travis/.local/include/openturns/OTconfigureArgs.hxx
-- Up-to-date: /home/travis/.local/include/openturns/OTconfig.h
-- Installing: /home/travis/.local/bin/openturns-config
-- Installing: /home/travis/.local/lib/cmake/openturns/OpenTURNS-Targets.cmake
-- Installing: /home/travis/.local/lib/cmake/openturns/OpenTURNS-Targets-release.cmake
-- Installing: /home/travis/.local/lib/libOT.so.0.0.0
-- Installing: /home/travis/.local/lib/libOT.so.0
-- Installing: /home/travis/.local/lib/libOT.so
```

**Comment by jschueller** [comment]
-1

**Comment by jschueller** [comment]
I think you could modify lib/CMakeLists.txt to install into ${INCLUDE_PATH}/\${PACKAGE_NAME}:
```
install (FILES ${HEADERFILES}
           DESTINATION ${INCLUDE_PATH}
        )
```

**Comment by dbarbier** [comment]
Oops, thanks @jschueller, should be fixed now.

**Comment by jschueller** [comment]
+1

**Pull request merged**
