### PR TITLE
Fixing KrigingResult with StationaryFunctionalCovarianceModel

### LINKED ISSUE #1861: Still some instabilities in Kriging with ot.StationaryFunctionalCovarianceModel
Hi
Seem all classes have not been updated by using conditional `TBB::ParallelForIf`

Here is a basic example :
```
import openturns as ot
rho = ot.SymbolicFunction("tau", "exp(-abs(tau))*cos(2*pi_*abs(tau))")
model = ot.StationaryFunctionalCovarianceModel([1],[1], rho)
x = ot.Normal().getSample(20)
y = x + ot.Normal(0,0.1).getSample(20)

algo = ot.KrigingAlgorithm(x, y, model, ot.LinearBasisFactory().build())
algo.run()
result = algo.getResult()
variance = result.getConditionalMarginalVariance(x)
print(max(map(lambda x: abs(x), variance)))

ot.TBB.Disable()
algo = ot.KrigingAlgorithm(x, y, model, ot.LinearBasisFactory().build())
algo.run()
variance = result.getConditionalMarginalVariance(x)
print(max(map(lambda x: abs(x), variance)))
```

As an example, output is 
```
0.0002485603814627634
3.469446951953614e-18
````
First value varies whereas second one is still the same around 0

### PR DESCRIPTION
**Pull request by sofianehaddad**
Fix #1861

### CODE REVIEW

**Review by jschueller — APPROVED** [review]

**Comment by jschueller** [comment]
you can rebase to get the ipopt fix

**Comment by sofianehaddad** [comment]
Done

**Comment by sofianehaddad** [comment]
@jschueller failing test is due to `Timeout`. When do you plan to merge this?

**Comment by jschueller** [comment]
Good for me, maybe @regislebrun wants to chime in

**Review by regislebrun — APPROVED** [review]
Looks good to me

**Pull request merged**
