### PR TITLE
Compact parameters

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by sofianehaddad** [comment]
+1

**Comment by jschueller** [comment]
@regislebrun, getParameterDimension or getParametersDimension, I see both in the code.

**Comment by regislebrun** [comment]
getParameterDimension(). In several places we hesitate between singular and plural nouns, but singular is more natural when talking about parameter space. And there is only one parameter, with dimension >=1 ;-)!

**Comment by jschueller** [comment]
@regislebrun, thanks, so getparametersdescription must be renamed too!

**Comment by regislebrun** [comment]
I think so. The same naming problem occurs in PR#50 on the new parameterization of the covariance models.

**Comment by jschueller** [comment]
@regislebrun , maybe I shoud rename DistributionParameters too ?

**Comment by sofianehaddad** [comment]
+1

**Pull request merged**
