### PR TITLE
 	Use viewer in Mesh docstrings

### PR DESCRIPTION
**Pull request by jschueller**
This works around a segfault in docstring_geom test on osx, cc @sofianehaddad

### CODE REVIEW

**Comment by jschueller** [comment]
Is this ok to go in @sofianehaddad @regislebrun @dbarbier

**Comment by regislebrun** [comment]
+1

**Comment by sofianehaddad** [comment]
This fix the random segfault on osx?

**Comment by jschueller** [comment]
@sofianehaddad It avoids it, drawing R graphs in docstrings resulted in segfault.

**Comment by sofianehaddad** [comment]
ok for the fix, thanks. +1

I should investigate later the real problem.

**Pull request merged**
