### PR TITLE
Fixed BernsteinCopulaFactory

### PR DESCRIPTION
**Pull request by regislebrun**
The BernsteinCopulaFactory class produces a Mixture which is a copula but it cannot be deduced from the individual properties of the atoms in the mixture.

### CODE REVIEW

**Comment by jschueller** [comment]
so if you save/load the result of BernsteinCopulaFactory the isCopula flag goes from true to false as it's not saved in distributionimplementation and takes its default value

**Comment by dbarbier** [comment]
+1

**Comment by jschueller** [comment]
+1

**Comment by jschueller** [comment]
Maybe CopulaImplementation:::isCopula can be removed too while only its flag would be set

**Comment by regislebrun** [comment]
@jschueller Yes, isCopula() should be removed from all the distributions/copulas, but it would take more time than I can afford right now, and the key point was to fix a bug with this PR. Of course it has to be done at a point, so I open a ticket.

**Comment by jschueller** [comment]
No, it's just that one:
```
$ grep -nr '::isCopula' schueller/lib/src/
schueller/lib/src/Uncertainty/Model/Distribution.cxx:611:Bool Distribution::isCopula() const
schueller/lib/src/Uncertainty/Model/DistributionImplementation.cxx:2391:Bool DistributionImplementation::isCopula() const
schueller/lib/src/Uncertainty/Model/CopulaImplementation.cxx:287:Bool CopulaImplementation::isCopula() const
schueller/lib/src/Uncertainty/Distribution/Mixture.cxx:528:Bool Mixture::isCopula() const
```

**Comment by regislebrun** [comment]
@jschueller I made a confusion between isCopula (only a few instances) and isIndependent() or isElliptical()!

**Comment by jschueller** [comment]
oh, theres also PythonDistributionImplementation

**Comment by regislebrun** [comment]
@jschueller This one has to stay like this, because the user may want to implement a copula using the PythonDistributionImplementation class and there is no way to set the isCopula_ member directly from python (or tell me how to do it ;-)).

**Pull request merged**
