### PR TITLE
Add RegisteredFactory for PersistentCollection<Basis>

### PR DESCRIPTION
**Pull request by aurelieladier**

### CODE REVIEW

**Comment by jschueller** [comment]
+1

**Comment by sofianehaddad** [comment]
+1, I had it on a local branch.
Thank you

**Comment by jschueller** [comment]
@sofianehaddad, if you've got other bug-fixes please share! Aurélie spent time debugging this.

**Comment by sofianehaddad** [comment]
@jschueller sorry the bug was reported by one of my collegues yesterday.

**Comment by jschueller** [comment]
@sofianehaddad, ok, we were out of luck this time : )

**Comment by dbarbier** [comment]
If this change fixes a bug, it should be described in the commit log.

**Pull request merged**
