### PR TITLE
Remove SubSquareCopula

### PR DESCRIPTION
**Pull request by dbarbier**
This class has never been compiled, but appears in doc.
Also remove lib/test/res file, it has likely been added by accident.

### CODE REVIEW

**Comment by regislebrun** [comment]
I agree on the fact that only part of this class has been implemented, but it is already a significant amount of work and I don't want to loose it. As it has been developed prior to the use of git, I have no branch dedicated to this specific development. Is it possible to store it in a dedicated branch before to remove these files? I don't know how to do it by myself.
BTW, RungeKutta and Fehlberg are there to implement the SubSquareCopulaFactory class.

**Comment by jschueller** [comment]
It's not lost, you can still restore it by something like ```git checkout <commit> <file>```.

**Comment by dbarbier** [comment]
For instance
```
git checkout tags/v1.10 -- lib/src/Uncertainty/Distribution/SubSquareCopula.cxx
```

**Comment by jschueller** [comment]
@regislebrun what about the TracyWidom distributions (http://trac.openturns.org/ticket/690) ?
They seem to implement moment and are not documented, imho they should go to.

**Comment by regislebrun** [comment]
@jschueller Exact. You can remove them too.

**Pull request merged**
