### PR TITLE
Use assignment operator for simple datatypes

### PR DESCRIPTION
**Pull request by dbarbier**
For performance reasons, constructors (and not assignments) are called to instantiate any object in local variables.  Current coding policy also enforces using constructors for plain old data structures.  There is no performance gain in this case, the only reason is consistency.

But several of us found assignment operators more readable.  Here are two commits to replace all occurences of
```
  const UnsignedInteger var(...);
```
by
```
  const UnsignedInteger var = ...;
```
Since lots of files are modified, this PR will conflict with any other PR.  So it should not be merged as is, but regenerated by running commands mentioned in these commits.

### CODE REVIEW

**Comment by jschueller** [comment]
+1, will apply this before branching 1.8

**Comment by regislebrun** [comment]
+1

**Comment by adutfoy** [comment]
+1

**Comment by jschueller** [comment]
see #271

**Pull request closed without merging**
